### ISSUE TITLE
Duda tipo de dato para los atributos

### ISSUE THREAD

**Issue by Dunkan1** [IIC2413/Syllabus-2018-2#10]
Hola, estaba leyendo y vi que sqlite no soporta booleans, asi que me preguntaba si teniamos que poner int o lo dejamos de igual manera como boolean
![imagen](https://user-images.githubusercontent.com/26102365/44439247-2e4a4a00-a599-11e8-9576-7599249e0cad.png)

Desde ya gracias, Saludos.

**Comment by alanezz** [comment]
Hola,

Si te refieres al proyecto, el esquema que diseñes puede implementarse de distintas maneras en los distintos sistemas. Si quieres utilizar un boolean tienes que declararlo como tal porque "se lee mejor". Además en el proyecto utilizarás PostgreSQL, por lo que no tendrás este problema.

Saludos!

**Comment by Dunkan1** [comment]
Hola, si me refería a la entrega, pero es bueno saber que usaremos PostgreSQL, gracias
