### ISSUE TITLE
Aclaraciones para la entrega 3

### ISSUE THREAD

**Issue by alanezz** [IIC2413/Syllabus-2018-2#101]
Estimados, subo esta issue para aclarar un par de aclaraciones del proyecto en base a las preguntas frecuentes que pueden llegar a tener.

### ¿Qué tengo que hacer?

En esta entrega deben volver a desarrollar una aplicación web muy similar a la anterior. Esta vez el foco está en:

1. Integrar dos bases de datos distintas: como dice el enunciado, está **prohibido** migrar tablas de la base de datos de un grupo a la de otro, salvo por la relación de usuarios. Esta pueden volver a construirla como estimen conveniente.
2. Manejar usuarios: deben manejar sesiones para tener un perfil de usuario. Esto puede tomarles algo de tiempo, pero un buen punto de partid es buscar en google por _sessions php_.

### ¿Todas las funcionalidades valen lo mismo?

No, las funcionalidades más importantes son:

1. Poder iniciar sesión
2. Poder comprar productos y que esto se refleje en la base de datos de pagos y en las compras de la tienda.
3. Poder transferir NebCoins entre usuarios.
4. Ver el historial de compras de un usuario.

### ¿Qué debe incluir el readme de la App?

El readme debe ser una guía sobre como navegar la app. En lo posible debería ser algo así.

>_Para poder comprar un producto, deben ingresar a la ruta `xxxx` y hacer click en `xxxx`._

Si su página web no se entiende y no se puede navegar, no va a ser corregida. Además se espera que en el readme **señalen al menos un usuario y su contraseña para poder navegar**. Ese usuario debe tener compras que se puedan ver en su perfil.

### ¿Puedo agregar tuplas a mi base de datos?

Sí, de hecho esto va a tener que pasar cuando vayan navegando y comprando en su tienda. Pero se espera que **todos los datos entregados estén cargados en la base de datos, y esto se refleje en la aplicación**.

### ¿Cómo se tiene que ver mi página web?

Si bien, en este curso no pedimos una página web estética, si es necesario que tenga un mínimo de navegación. Tiene que haber un index donde yo puedo buscar productos, y existe una forma de ingresar a una página de producto. Esto es como cuando navegan por una tienda en línea, y le hacen click a un producto en particular, por ejemplo, un computador. Pueden ver detalles de ese computador en específico. Para esto deben manejar rutas dinámicas, que reciben un id de producto, y dependiendo de ese id, van a hacer una consulta en la db y cargan los datos. Lo mismo para los perfiles, las compras etc. Mientras más real sea la experiencia de navegación por su tienda / sistema de NebCoins, es porque mejor les está quedando la aplicación.

### Aparte de usar sólo consultas, ¿puedo programar en PHP?

Sí, es posible que necesiten obtener ciertos resultados calculando valores en PHP.

### El grupo con el que me asignaron no aparece

En este caso, deben contactarme con urgencia. Si se llega a identificar que alguien no trabajó en esta entrega **va a tener la nota mínima**. Después de la entrega habrá una evaluación de pares.

Usen bien el tiempo para esta entrega y no dejen todo a última hora.

**Comment by PIPEAPABLAZA** [comment]
Los archivos php/html para la nueva página también van en la carpeta sites del grupo menor?

**Comment by jmwielandt** [comment]
probé y no puedo desde un grupoXX acceder al `psql grupoYYE3` de otro grupo, así que asumo que los csv para ingresar las tablas deben estar en los grupos respectivos, correcto?
