### ISSUE TITLE
Uso de Tablas en Procesos Almacenados

### ISSUE THREAD

**Issue by aeavalos** [IIC2413/Syllabus-2018-2#106]
Si quiero utilizar una tabla en un Proceso Almacenado, puedo llamarlo como un parámetro de esta "función":
CREATE OR REPLACE FUNCTION
nombre_proceso (A table, B table)

¿O tengo que llamarlo dentro del proceso, donde la tabla estaría hecha desde antes?
Desde ya muchas gracias por su tiempo 😄

**Comment by alanezz** [comment]
Hola,

No se puede como tal, te dejo este [https://dba.stackexchange.com/questions/204639/postgres-declare-table-as-a-parameter-for-a-function](link) que lo explica. Desde ahí encontrarás este [https://stackoverflow.com/questions/18384159/define-table-and-column-names-as-arguments-in-a-plpgsql-function/18386034#18386034](post) que plantea una solución. Básicamente es pasar el nombre de la tabla como string y después hacer FORMAT en el procedimiento.

Saludos.

**Comment by aeavalos** [comment]
Gracias 😄
