### ISSUE TITLE
Formato de Fechas en Pagos.csv

### ISSUE THREAD

**Issue by leolivares** [IIC2413/Syllabus-2018-2#107]
Hola!
Estaba revisando las fechas de transacción en el archivo Pagos.csv, y algunas de ellas se encuentran en el formato (dd/mm/yyyy) y otras en (mm/dd/yyyy).
En algunos casos, no es posible saber si se trata de un mes o un dia, debido a como varian los formatos.
Que hacemos en este caso?

**Comment by MarceloSaldias** [comment]
Subieron cambios a los csv con las fechas bien puestas! 😄
