### ISSUE TITLE
Bases de Datos E3

### ISSUE THREAD

**Issue by aeavalos** [IIC2413/Syllabus-2018-2#109]
La única diferencia entre los datos de los Excels de la carpeta "Entrega 3" y "Entrega 2" es que los usuarios tienen una clave? O existen nuevos datos a considerar?

**Comment by aeavalos** [comment]
Además, cuando trato de importar los datos de "Usuarios.csv" a psql me aparece el siguiente error:

                               invalid byte sequence for encoding "UTF8": 0xd3 0x4e
A qué se debe eso?

**Comment by alanezz** [comment]
Hola,

Los datos son casi los mismos, salvo que se agregaron algunas tuplas que faltaban (por ej, usuarios fantasmas) y algunas columnas aparte de la clave. 
Sobre la segunda pregunta, puedes encontrar [https://stackoverflow.com/questions/4867272/invalid-byte-sequence-for-encoding-utf8](aquí) una respuesta. Me tinca que abriste el csv con algún programa tipo excel y al guardarlo le cambias el encoding.

Saludos.

**Comment by aeavalos** [comment]
Gracias 😄
