### ISSUE TITLE
Duda formato PRIMARY KEY

### ISSUE THREAD

**Issue by Regenschrim** [IIC2413/Syllabus-2018-2#11]
Duda corta con respecto a la escritura de la PRIMARY KEY, ¿es necesario que esta este al principio de la declaración de atributos o pueden ir en cualquier orden?

**Comment by nivek0o0** [comment]
Hola,
en sqlite3, cuando la llave primaria se compone de un solo atributo, éste puede estar ubicado en cualquier posición. Cuando la llave tiene 2 atributos o más, se debe usar el argumento PRIMARY KEY(at1, at2, ...) y debe entregarse después de declarar todos los atributos.

**Comment by Regenschrim** [comment]
Perdón, creo que me explique mal jaja me refiero a cuando definamos las tablas de la entrega, no directamente en sqlite3. Iba a poner un ejemplo pero supe como subrayar :/

**Comment by rfenzo** [comment]
Lo ideal es que coloques los atributos que son  primary keys antes que los demas atributos, por claridad, pero no hay problema con que no estén en orden.

**Comment by Regenschrim** [comment]
Ya, muchas gracias! 😄
