### ISSUE TITLE
usuarios 'no aplica'

### ISSUE THREAD

**Issue by beayancan** [IIC2413/Syllabus-2018-2#111]
Actualizando la tabla de usuarios se tiene que estos ahora tienen claves, pero además al final se agregaron tiendas para los cuales ciertos atributos aparecen como no aplica. ¿la idea es que los manejemos como un conjunto o bien podemos separarlos de acuerdo a lo que consideremos?

**Comment by alanezz** [comment]
Hola,

Eso lo pueden manejar como ustedes quieran mientras se cumplan los requerimientos del enunciado. No están obligados a usar un esquema en particular.

Saludos.
