### ISSUE TITLE
Error psycopg2

### ISSUE THREAD

**Issue by FernandoDeDiego** [IIC2413/Syllabus-2018-2#112]
Hola!
Estoy tratando de correr un archivo python, pero al tratar de conectar a postgress me aparece el siguiente error:

__could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?__

Cómo puedo solucionarlo?
Saludos!!

**Comment by alanezz** [comment]
Hola,

Tienes instalado Postgres en tu computador? No te va a funcionar si desde tu computador intentas conectarte al servidor.

Saludos.

**Comment by FernandoDeDiego** [comment]
No lo tengo instalado. Cómo lo corro desde el servidor? Creo que no me quedó muy claro :/

**Comment by twallacech95** [comment]
yo tambien tengo este problema!

**Comment by felipesilvadv** [comment]
Hola! Para correrlo en el servidor(vía filezilla o scp), tienes que subir tu código, luego conectarte vía terminal o putty,
```
ssh grupoXX@bases.ing.puc.cl
```
 una vez dentro usas: 
```
cd carpeta_donde_guardaste
python3 tu_codigo.py 
```
y con eso correrás el código en el servidor.

**Comment by alanezz** [comment]
La otra opción es instalar PostgreSQL en tu computador y programar ahí. Instalar PostgreSQL no es tan sencillo y depende del sistema operativo. Lo más fácil es en OSX, en el que existe la Postgres App. Pero hay tutoriales para [Windows](http://www.postgresqltutorial.com/install-postgresql/) y [Ubuntu](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-postgresql-on-ubuntu-18-04).

Cuando instalas Postgres puedes dejar corriendo el server de psql en tu computador. Luego te conectas vía terminal y puedes hacer consultas vía terminal, como cuando te conectas a tu server del proyecto.

Saludos.

**Comment by FernandoDeDiego** [comment]
Ok, muchas gracias!
