### ISSUE TITLE
Inconsistencia nulos postgress (en el server) [autorresuelto]

### ISSUE THREAD

**Issue by jmwielandt** [IIC2413/Syllabus-2018-2#114]
Hola,
Estoy revisando la materia de nulos y me topé con una inconsistencia extraña, 
si tengo la tabla R

|a | b|
|--|--|
|1|2|
|2|3|
|3|4|
|null|8|

y la tabla S

|a|c|
|--|--|
|1|4|
|5|8|
|3|null|
|null|-44|

La consulta `select * from r where r.a in (select a from s);` me retorna 

|a|b|
|--|--|
|1|2|
|3|4|

Pero la consulta `select * from r where r.a not in (select a from s);` me retorna una tabla vacía.
En las diapos explica esto último con que para un valor de r.a la consulta ` r.a in una_tabla_con_nulos` es `unknown` y el `not unknown` sigue siendo `unknown` (nunca sabe si no está en la tabla), por lo que retorna vacío, pero... ¿por qué si le saco el not sí me retorna cosas? Si no sabe que no está, no debiera poder saber que está, o sí?

Siento que por alguna razón esto no me debiera sorprender pero sí lo hace 🤔 

![imagen](https://user-images.githubusercontent.com/37153467/47052464-d84fe800-d17e-11e8-9eae-f8d5a25f9d08.png)

(en grupo39stored están mis tablas R y S o.o)

**Comment by jmwielandt** [comment]
Seguí pensando mientras comía y creo que ya sé por qué pasa

1 in {1, 5, 3, null} -> true
2 in {1, 5, 3, null} -> unknown

pero 
1 not in {1, 5, 3, null} -> unknown
2 not in {1, 5, 3, null} -> unknown

Entonces en el primer caso hay valores que sí entran
y en el segundo o no está o no sabes, entonces nunca entra.
Gracias~
¿la dejo abierta o la cierro?

**Comment by alanezz** [comment]
La respuesta es tal como dices 👌
