### ISSUE TITLE
¿Cómo sé qué funciones están creadas?

### ISSUE THREAD

**Issue by jmwielandt** [IIC2413/Syllabus-2018-2#116]
Sé que con `\d` puedo saber todas las tablas pero no encuentro cómo saber cuales son las funciones que están creadas.
Además... ¿cómo elimino funciones en caso de necesitarlo? u.u

**Comment by alanezz** [comment]
Hola,

Aquí sale como listar funciones: https://stackoverflow.com/questions/1347282/how-can-i-get-a-list-of-all-functions-stored-in-the-database-of-a-particular-sch

Respecto a eliminarlas, se hace con Drop Function.

**Comment by jmwielandt** [comment]
Gracias~
