### ISSUE TITLE
[Proyecto] Cambios en las tablas

### ISSUE THREAD

**Issue by beayancan** [IIC2413/Syllabus-2018-2#119]
Hola,
Las bases de datos que aparecen para esta entrega (exceptuando usuarios) ¿qué tan distintos son de las tablas para la entrega 2? ¿Habría que realizar nuevamente el proceso de separarlas y arreglar los datos con Python 👨‍🎨 ?

Saludos.

**Comment by FernandoPieressa** [comment]
Tienen algunas modificaciones, por lo que se recomienda trabajar con las nuevas tablas, pero en si son muy parecidas, por lo que si vas comparando y hay alguna que se ve igual la pueden reutilizar

Saludos!

**Comment by nfbalbontin** [comment]
Me surge una duda con respecto a esto, en el enunciado sale: 
"Para trabajar en esta entrega no se permite migrar todo el esquema a la base de datos de uno de los grupos, sino que se deben manejar cada una en el servidor respectivo. La idea de esto es mantener dos conexiones abiertas."
Por lo que uno asume que trabajará con las tablas ya generadas en la entrega pasada para ocupar ambos servidores. Pero al dar nuevos datos se tienen que generar nuevas tablas, y esas tablas por facilidad se harán en solo un servidor, entonces, ¿Cuál es la necesidad de ocupar ambos servidores si se generarán nuevas tablas con los nuevos datos?

**Comment by alanezz** [comment]
Se respondió en #126. Se entiende que por facilidad podrías hacer todo en un servidor. Pero la idea es aprender a integrar datos con dos conexiones distintas.
