### ISSUE TITLE
Sobre funcionamiento enunciado impar

### ISSUE THREAD

**Issue by jmwielandt** [IIC2413/Syllabus-2018-2#12]
Hablando con mi compañero hay algunas cosas que no nos quedan del todo claras.

1. **Abonos**:  "debe hacer un cargo a una de sus tarjetas de créditos" ¿Esto es que el usuario mete plata en una de sus tarjetas? ¿O que le cobra a la tarjeta para cargar nebcoins al banco?
2. ¿Las transacciones se hacen desde una tarjeta o desde un usuario?
3. "El valor de la NebCoin en ese momento" ¿qué es esto? ¿Algo como el valor del bitcoin en dólares?
4. ¿El seguro es sobre un usuario o sobre una tarjeta?
5. ¿Las transacciones son entre usuarios? La consulta 2 habla de "tienda" pero no hay información sobre eso en ningún lado.
6. ¿Pueden explicar el sistema **completo** del banco, nebcoins, tarjetas de crédito y las nebstores? Para así entender bien qué nos están pidiendo. Gracias. PD: sin esta información nos es imposible avanzar con alguna mínima certeza de que lo que hacemos está bien.

**Comment by alanezz** [comment]
Hola, voy a ir pregunta por pregunta:

1) Piensa que estás transformando dinero de verdad en NebCoins y quedan en tu cuenta (esto es como Paypal o como un exchange de ciptomonedas). La tarjeta de crédito a la que se hace referencia es de un banco convencional. Interesa que en el sistema quede registrado cuantas NebCoins compraste, el valor de una NebCoin en ese momento, la fecha y la tarjeta que utilizaste para hacer el pago (ya que puedes tener más de una en el sistema).
2) Las transacciones se hacen desde un usuario, las tarjetas sólo sirven para abonar.
3) Exacto, como toda moneda tiene un valor en dolares o CLP.
4) Nuevamente, el seguro es para un usuario. Las tarjetas sólo sirven para abonar.
5) Lo aclaré en el siding, son entre usuarios, pero la cuenta de destino probablemente va a representar a una tienda.
6) No necesitas conocer el sistema completo para esta entrega. Necesitas realizar el esquema acotado de lo que se pide en el enunciado que te corresponde. Si quieres saber la info completa, puedes leer el enunciado par. La idea es que en cierto momento del semestre se junten ambos sistemas, en donde cada pago en NebCoins represente la compra de un usuario a una tienda (esto es parte del enunciado del grupo par).

Saludos!

**Comment by jmwielandt** [comment]
Muchas gracias~
