### ISSUE TITLE
Pagos y compras

### ISSUE THREAD

**Issue by diegoheg** [IIC2413/Syllabus-2018-2#120]
Hola! Con mi grupo tenemos la duda de como asociar las compras de productos y servicios con los pagos, ya que no hay ninguna tabla que los relaciones, ni ninguna forma de asociarlos. Esto para mostrar las cuotas de las compras en la página de perfil. ¿O es qué solo debemos mostrar las cuotas de las transferencias entre usuarios y no de las compras?

**Comment by FernandoPieressa** [comment]
Hola! Para los datos de la base de datos actual, basta con que muestren las cuitas de las transferencias entre los usuarios, pero a partir de las nuevas compras que se generen en su programa, se tiene que controlar todo.

De todas formas, lo pueden asociar las compras y pagos mediante la comparación del el usuario1 del pago, usuario2 del pago, fecha y monto respecto a la de la tabla de compras (Este podría no ser único pero es difícil que sea todo igual en términos de esta entrega)

Saludos!

**Comment by valerojasm** [comment]
Hola! No entendí muy bien a qué ibas con esto: `De todas formas, lo pueden asociar las compras y pagos mediante la comparación del el usuario1 del pago, usuario2 del pago, fecha y monto respecto a la de la tabla de compras (Este podría no ser único pero es difícil que sea todo igual en términos de esta entrega)`

**Comment by stephichau** [comment]
@FernandoPieressa se referia de que puedes asociarlo con esos atributos con los datos entregados. Sin embargo, éstos no necesariamente son únicos, es decir, un usuario puede realizar una compra o pago a otro usuario con la misma fecha y el monto más de una vez :)
