### ISSUE TITLE
Inicio sesión

### ISSUE THREAD

**Issue by jmwielandt** [IIC2413/Syllabus-2018-2#122]
Hola, es obligatorio que los usuarios inicien sesión con correo y contraseña o podemos asignarles un id único con el que deban iniciar sesión _para su mayor seguridad_?

**Comment by FernandoPieressa** [comment]
Es necesario que inicien sesion con correo y contraseña, piensa en todos los otros sitios web, complicaría mucho la usabilidad del programa y todo el mundo olvidaria su id.

Saludos!

**Comment by jmwielandt** [comment]
Gracias~
