### ISSUE TITLE
[P3] Cálculo saldo

### ISSUE THREAD

**Issue by jmwielandt** [IIC2413/Syllabus-2018-2#123]
Hola, 
Quería rectificar que el cálculo del saldo se mantiene como en la entrega pasada
![imagen](https://user-images.githubusercontent.com/37153467/47259614-06387380-d482-11e8-8fd4-f715eb96747e.png)

Porque si restamos los pagos realizados, podríamos estar restando al saldo el monto de cuotas que no han sido pagadas. Si entendí bien el sistema (y lo más probable es que no), 

`saldo = abonos + pagos_recibidos - pagos_realizados_al_contado - cuotas_de_pagos_pagadas`

**Comment by stephichau** [comment]
Hola! si, esta bien el calculo del saldo

**Comment by frduran** [comment]
Por qué se deben considerar las cuotas?

**Comment by alanezz** [comment]
Hola, pueden considerarlo como estimen conveniente, pero señalen en el readme lo que hicieron.

Saludos.
