### ISSUE TITLE
Perfil usuario

### ISSUE THREAD

**Issue by CmPoblete** [IIC2413/Syllabus-2018-2#124]
En el enunciado dice que un usuario para cada una de sus compras debe poder ver Todos los productos parte de la compra. Supongo es esto tambien incluye servicios o no? o lo dejamos solo a productos?

**Comment by valerojasm** [comment]
Tengo una pregunta sobre eso también. Por lo que tengo entendido cada id de compra está asociada a un solo producto, solo que en distintas cantidades - entonces no se a qué se refiere con mostrar los distintos productos de la compra. Esto significaría que id compra e id compra s (de servicios) están relacionados y cada compra es de un producto específico y un servicio específico? (que son la misma id en el fondo?)

**Comment by alanezz** [comment]
Respecto a lo primero, tienes que mostrar las compras de productos y compras de servicios. Piensa como usuario: sería súper malo por parte de la página no poder tener un historial de todo lo que compras. En realidad en vez de producto debería haber dicho algo así como "entidades pertenecientes a la compra".

Respecto a lo segundo. Cuando modificamos los datos, ahora en una compra puede haber más de un producto.

Saludos.

**Comment by valerojasm** [comment]
Perdón que vuelva a esto, no me quedó claro si la id_compra_s de los servicios y la id_compra de los productos hacen referencia a una misma compra, en el fondo que cada compra involucra tanto productos como servicios, o son separados?

Gracias!

**Comment by alanezz** [comment]
Hola,

Los datos están hechos de manera tal que las compras van a contener solamente productos, o solamente servicios.

Saludos.
