### ISSUE TITLE
Nueva base de datos

### ISSUE THREAD

**Issue by valerojasm** [IIC2413/Syllabus-2018-2#126]
Hola!

Tengo una pregunta, se supone que tenemos un nuevo servidor para este entrega, pero a la vez el enunciado pide que trabajemos con la integración de dos servidores, entonces no entiendo. Cuál hay que usar? Porque si usamos el nuevo tendríamos que tener todas las tablas ahí y perdería lo de usar dos servidores distintos, no?

Muchas gracias!

**Comment by alanezz** [comment]
Hola,

Estás confundiendo conceptos. Tu grupo se conforma de dos grupos de la entrega pasada. Cada uno tiene un servidor distinto. La idea es que los datos que corresponden a cada grupo tienen que seguir en el servidor respectivo. La idea es aprender a trabajar con dos conexiones.

Sin embargo, para esta entrega les dimos una nueva base de datos (no un nuevo servidor). Esto es porque no queremos que toquen las tablas de la entrega 2, porque tienen que seguir funcionando. Entonces si en esta entrega cambias algo, puede que tu entrega anterior deje de funcionar si usaban la misma base de datos.

Entonces, cada grupo tiene una nueva base de datos en donde deben cargar los datos correspondientes a ese grupo, y después deben manejar la integración con dos conexiones abiertas.

Saludos.

**Comment by stephichau** [comment]
Hola @nfbalbontin!

Tal como dice @alanezz, 

> La idea es que los datos que corresponden a cada grupo tienen que seguir en el servidor respectivo. La idea es aprender a trabajar con dos conexiones.

> Entonces, cada grupo tiene una nueva base de datos en donde deben cargar los datos correspondientes a ese grupo, y después deben manejar la integración con dos conexiones abiertas.

Si bien funcionaría igual teniendo todo en un servidor, eso no es lo que se está evaluando.

Saludos :)

**Comment by nfbalbontin** [comment]
mmmm... Aún seguimos medios confusos. Entendemos que quieren que hagamos consultas de dos servidores distintos  - en nuestro caso Grupo7 y Grupo50-  y esos servidores cuentan con una base de datos propia - Grupo7 y Grupo50-. Pero la cuestión es no alterar esas bases de datos para la corrección pasada, por lo que nos dan una nueva base de datos - grupo7E3 -. Ahora, si lo que se quiere es que las consultas provengan de una combinación de servidores, y supongo que de esto, de sus propia bases de datos, ¿cuál es la idea de la nueva base de datos? ¿No sería mejor agregar nuevas tablas a las bases de datos antiguas de tal forma que no se altere la información que existe y de esa forma ocupar esta mezcla de servidores? En el fondo, seguimos sin entender la utilidad de la nueva base de datos.

**Comment by alanezz** [comment]
Hola,

Tienen dos bases nuevas, grupo7E3 y grupo50E3. Tienen que cargar las tablas respectivas a cada uno de los servidores.

Saludos.

**Comment by nfbalbontin** [comment]
Excelente. Eso era lo que no sabíamos, pensábamos que era solo 1. Muchas gracias.
