### ISSUE TITLE
Formato fechas

### ISSUE THREAD

**Issue by frduran** [IIC2413/Syllabus-2018-2#127]
Importa como manejo las fechas en mi base de datos? Ya sea dd/mm/yyyy, yyyy/mm/dd, dd-mm-yyyy o yyyy-mm-dd 
Gracias de antemano!

**Comment by alanezz** [comment]
Hola,

No importa mientras las consultas y la aplicación en general funcione según lo esperado.

Saludos.

**Comment by frduran** [comment]
Gracias!
