### ISSUE TITLE
Eliminar tarjeta

### ISSUE THREAD

**Issue by Dyoma3** [IIC2413/Syllabus-2018-2#128]
Al eliminar una tarjeta de crédito, se tienen que eliminar también los abonos correspondientes a esa tarjeta? No me hace tanto sentido, pero el problema (o no) en el caso de no eliminarlos es que quedarían abonos con id s de tarjetas que ya no están en la base de datos.

Gracias de antemano!

**Comment by beayancan** [comment]
Me sumo a esta consulta, ¿al borrar la tarjeta debemos borrar igualmente los abonos que realizó con ella?

**Comment by alanezz** [comment]
Hola,

Si una tarjeta se borra no puedes borrar los abonos, piensa que no quedaría registro de la plata. La solución elegante es hacer un _soft delete_, en que hay una columna en la tabla de tarjetas que indica si está activa o no. En caso de eliminarla puedes seguir viendo los abonos que hiciste con las tarjetas que "ya no están".
Otra solución es eliminar la tarjeta, pero no eliminar los abonos. Al momento de hacer el join para saber con qué tarjeta se hizo el abono, haces un outer join, y te devolvería un nulo, pero de todas formas aparecería el abono.
Finalmente, está la opción de que no te deje borrar la tarjeta, que sigue siendo válida.

Puedes tomar la determinación que te parezca razonable.
