### ISSUE TITLE
Sobre requerimientos obligatorios

### ISSUE THREAD

**Issue by felipe8797** [IIC2413/Syllabus-2018-2#13]
En el enunciado par, se menciona que deben estar obligatoriamente las clases "tienda producto" y "tienda servicio". ¿Es posible hacer solo una clase que sea "tienda" y manejar las diferencias con atributos ?
Gracias!

**Comment by alanezz** [comment]
Si crees que puedes responder las consultas con esa modelación puedes hacerlo. En esta entrega no se evalúa que la modelación sea correcta, porque aún no aprendemos a modelar.

Saludos!
