### ISSUE TITLE
Busqueda de productos y Página de Producto

### ISSUE THREAD

**Issue by beayancan** [IIC2413/Syllabus-2018-2#131]
En las consultas se tiene que los usuarios deben ser capaces de buscar un producto o servicio, para acceder a ellos. En la consulta siguiente se pide poder acceder al producto o servicio en particular, con toda la info.

No veo mucha diferencia entre ellas ¿Estas consultas son complementarias? es decir ¿por medio de la búsqueda de un producto puedo llevarlo a la pagina del producto cumpliendo ambas consultas? o bien ¿para la consulta de pagina de producto es necesario acceder a ella de forma distinta?

**Comment by alanezz** [comment]
Hola,

Piensa en una tienda estilo amazon. Cuando buscas algo, te aparece una página con un listado de los productos que se parecen a lo que buscaste. Luego le haces click a un producto y accedes a ese producto en particular, viendo los detalles.

Saludos.

**Comment by beayancan** [comment]
Si entiendo bien, entonces en la consulta **Búsqueda de productos y servicios** debo ser capaz de buscar un producto y servicio ingresando el nombre de este

En cambio en la consulta **Página de producto o servicio** debe ser estilo amazon (?), cuyo método de búsqueda no me queda claro.
