### ISSUE TITLE
Instalación MongoDB

### ISSUE THREAD

**Issue by CristobalHV** [IIC2413/Syllabus-2018-2#133]
Hola, quería preguntar lo siguiente

Que opción debo escoger para continuar la instalación?

![image](https://user-images.githubusercontent.com/37159539/47396948-6722ae80-d703-11e8-980a-dc1501970104.png)

Instalo MongoDB como servicio? De ser servicio, que opción debería escoger?

Gracias!

**Comment by alanezz** [comment]
Hola,

Cómo lo estás instalando? En el [tutorial](https://docs.mongodb.com/v3.2/tutorial/install-mongodb-on-windows/) oficial no sale nada al respecto.

Saludos.

**Comment by CristobalHV** [comment]
Estoy usando el archivo .msi de instalación de MongoDB

En el mismo tutorial sale esto
![image](https://user-images.githubusercontent.com/37159539/47501611-5033a780-d83c-11e8-845d-b70ffd12d667.png)
Pero desconozco que opción tomar una vez llegado al pantallazo de arriba

saludos

**Comment by alanezz** [comment]
Yo creo que lo correcto es no instalarlo como servicio, para que no esté todo el rato escuchando conexiones. Prueba haciendo lo mismo que aparece [acá](https://www.youtube.com/watch?v=bkVd5AFmD74).

Saludos.

**Comment by aeavalos** [comment]
Lo hago como en el video, pero igual llego a la ventana que mandó mi compañero. Lo hago exactamente igual que en el video, a qué se puede deber esto?

**Comment by beayancan** [comment]
Me aparece lo mismo. En el tutorial oficial si aparece
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/
