### ISSUE TITLE
TiendaDeServicios.csv

### ISSUE THREAD

**Issue by auirarrazaval** [IIC2413/Syllabus-2018-2#134]
Hola!

Al intentar usar el comando \copy para poder insertar los datos a mi relacion, me tira un error de que hay mas columnas de las esperadas dado que la ubicacion esta en formato "DIRECCION **,** ESTADO ZIP", y esa coma separa esto en dos mas, intente usando QUOTE, NULL y  todo lo que encontre en internet. Existe alguna otra forma de hacerlo? O puedo meter mano en el csv (pasarlo a tsv) para evitar este problema?

**Comment by stephichau** [comment]
Hola!

Puedes manejar los datos como más se te acomode

**Comment by gregschuit** [comment]
Hola! El problema son las comas entre filas, postgres cree que el archivo es un solo gran header. En mi grupo se las sacamos con Python y luego ingresamos la tabla al sistema con \copy
