### ISSUE TITLE
Revisión de información E3

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [IIC2413/Syllabus-2018-2#136]
Hola!

Para esta entrega, para probar algunas funcionalidades he tenido que agregar y quitar tuplas a las bases de datos. Cuando revisen cosas como por ejemplo transferencias históricas, estas tienen que coincidir con lo original?. En el fondo, debería deshacer los cambios que hice para probar? o da lo mismo?

**Comment by FernandoPieressa** [comment]
Sería ideal que estén los datos originales para facilitar la recorreccion, sin embargo mientras se mantenga gran parte de los datos originales, si varían algunos no sera problemático.

Saludos!
