### ISSUE TITLE
Duda transferencia y cuotas

### ISSUE THREAD

**Issue by CmPoblete** [IIC2413/Syllabus-2018-2#137]
Hola, al hacer una transferencia, esta se debe agregar a la tabla cuotas? En el enunciado sale que las tranferencias se hacen sin cuotas pero revisando las compras, todas las que fueron pagadas al contado tambien fueron agregadas a esta tabla por eso me entro la duda.

**Comment by FernandoPieressa** [comment]
Tienes que agregarla a la tabla cuotas. Considera que "sin cuotas" == "1 cuota"

Saludos!
