### ISSUE TITLE
Compras y saldo persona

### ISSUE THREAD

**Issue by valerojasm** [IIC2413/Syllabus-2018-2#138]
Hola! Una pregunta. Nosotros estamos considerando el saldo actual (en nebcoins) como la suma de (cantidad / valor nebcoin) de cada abono de cada tarjeta de una persona. 1) Está bien esto? 2) Los precios de los productos/servicios/seguros/etc están en nebcoins o en plata? Como para transformarlo antes de restarle la plata a la persona cuando los adquiera. Gracias!

Edit: Agrego a esta pregunta. Cuando dice: 

> o hacer un abono a su cuenta desde una de sus tarjetas de credito.

Asumo que puede abonar infinita plata a su cuenta? Ya que no tenemos información de cuanta plata tiene en la tarjeta?

**Comment by FernandoPieressa** [comment]
1) Esta mal, porque tienes que considerar tambien los pagos hechos por el usuario para calcular el saldo actual.
2)  En plata
3) Tal como dices, no hay informacion de cuanta plata por lo que pueden sacar infinita

Saludos!
