### ISSUE TITLE
Duda archivos php

### ISSUE THREAD

**Issue by legramsch** [IIC2413/Syllabus-2018-2#139]
Hola! mi duda es bien simple. En el trabajo, todos los archivos php deben estar en el mismo servidor? o pueden estar separados en los de cada grupo? (la tienda en el grupo par, y el banco y cuentas en el otro grupo, por ejemplo).

**Comment by CmPoblete** [comment]
Segun yo se tienen que subir en el mismo servidor

**Comment by FernandoPieressa** [comment]
Basta con que este en el mismo servidor, lo que se tiene que manejar entre ambos son las bases de datos

Saludos!
