### ISSUE TITLE
Duración de servicios y precio asociado

### ISSUE THREAD

**Issue by matiaszenteno** [IIC2413/Syllabus-2018-2#140]
Hola! con mi grupo nos surgieron dos dudas. Al momento de contratar un servicio, ¿el usuario elige la fecha de término de este? ¿y hay un costo asociado por la duración del mismo? 

gracias!

**Comment by alanezz** [comment]
No hay costo asociado con la duración. Respecto a lo otro, puedes hacerlo como tú quieras.

Saludos.
