### ISSUE TITLE
Informe y README

### ISSUE THREAD

**Issue by beayancan** [IIC2413/Syllabus-2018-2#142]
Hola, en el enunciado no se especifica pero quería estar seguro, ¿es necesario hacer un informe que explique el modelo como en la entrega anterior? y para el readme ¿hasta cuando tenemos fecha de subirlo?

**Comment by alanezz** [comment]
Hola, no hay un informe. El readme se sube junto con la entrega (no hay más plazo).

Saludos.

**Comment by TomasSalvadores** [comment]
El readme se sube a la carpeta entrega3 cierto?

**Comment by frduran** [comment]
En qué formato debemos hacer el readme? pdf, markdown... Gracias!

**Comment by alanezz** [comment]
Se sube en la carpeta de la entrega. Puede estar en PDF o Markdown, como ustedes prefieran.

Saludos.
