### ISSUE TITLE
Ayuda con Pycharm

### ISSUE THREAD

**Issue by frduran** [IIC2413/Syllabus-2018-2#148]
Hola! Si bien esto no es pregunta del curso me gustaría saber si alguien me puede guiar en cómo puedo renovar la licencia de Pycharm por favoooor!!
Gracias!

**Comment by alanezz** [comment]
Hola,

Según yo te llega un mail de JetBrains con asunto **Renew your JetBrains Student License**. Ahí hay un link para renovar la licencia por un año más mientras sigas siendo estudiante.

Saludos!

**Comment by frduran** [comment]
Gracias!
