### ISSUE TITLE
Consultas 4, 5 y 6 [IMPAR]

### ISSUE THREAD

**Issue by Taeval** [IIC2413/Syllabus-2018-2#15]
El enunciado dice que debemos escribir las primeras tres consultas en álgebra relacional. ¿Esto implica que las consultas 4, 5 y 6 NO hay que escribirlas? ¿Sólo sirven como guía para la delcaración de las relaciones?

**Comment by alanezz** [comment]
Exacto, no las tienes que escribir ni justificar nada. Es sólo para que las tengas presente, porque en el futuro las vas a tener que soportar.
