### ISSUE TITLE
Búsqueda por texto API

### ISSUE THREAD

**Issue by antoniacobo** [IIC2413/Syllabus-2018-2#150]
Hola! Para hacer búsqueda por texto en la api, se hace todo en un mismo link? Es decir, en un mismo request puedo hacer búsqueda literal, de palabras necesarias pero no obligatorias y de palabras que no pueden estas? ¿O se hace con un link para cada tipo de búsqueda?

En la misma línea de la pregunta, ¿se necesita hacer un index en MongoDB para que sea más rápido o no es necesario?

**Comment by stephichau** [comment]
hola!

Deben mezclarlo en un mismo lugar. Sobre los índices, puedes revisar [acá](https://docs.mongodb.com/manual/indexes/) :)

**Comment by akrebs2** [comment]
Hola, leí el link pero sigo con la misma duda, desarrollamos una "sintaxis propia" para diferenciar las consultas (explicándola en el readme) o cómo sería si no?

Gracias!

**Comment by akrebs2** [comment]
Perfecto. La única duda que me queda es con la parte que dice: 

> Para la búsqueda por texto sobre los mensajes, se debe poder consultar sobre todos los
mensajes en la base de datos, o sobre los mensajes emitidos por un usuario en particular.

En ese caso, ¿diferenciamos los dos tipos de consultas (con y sin especificar id de usuario)?

Gracias!

**Comment by alanezz** [comment]
Exacto.

**Comment by akrebs2** [comment]
Gracias profesor, perdón las molestias!

**Comment by alanezz** [comment]
No es una molestia 😄

Ánimo!
