### ISSUE TITLE
Latitud y longitud de mensajes para insertarlos a mongoDB

### ISSUE THREAD

**Issue by legramsch** [IIC2413/Syllabus-2018-2#152]
Hola, los mensajes tienen una variable longitud y una latitud. Al momento de insertar cada mensaje, ¿Esa debe ser la ubicación (o un estimado)? ¿Un valor al azar? ¿ Un valor fijo?
En caso de que sea la primera, se pueden usar modulos como urllib?

**Comment by alanezz** [comment]
Esa debe ser la ubicación. Puedes usar los módulos que estimes conveniente.

Saludos.
