### ISSUE TITLE
Consulta en Mongo con Text Search

### ISSUE THREAD

**Issue by aeavalos** [IIC2413/Syllabus-2018-2#162]
Al utilizar un índice en mongo, donde busco los datos que tienen en el una frase o una palabra sería válida la siguiente consulta?

`db.usuarios.find({$text: {$search: "\"frase uno\" palabra"}}, {});`

Dentro de lo mismo, si busco que tenga la "frase uno" o la "frase dos", ¿cómo lo hago? porque el siguiente código debería ser como un "and":

`db.usuarios.find({$text: {$search: "\"frase uno\" \"frase dos\""}}, {});`

Desde ya muchas gracias por tiempo 😄

**Comment by alanezz** [comment]
Hola,

La primera consulta debería exigir la frase y además deseablemente tener la palabra. Ideal si puedes probarlo tu mismo en el motor de db.

Para hacer la segunda consulta puedes usar el $OR de MongoDB (en la guía de mongo puedes ver cómo usarlo).

Saludos!

**Comment by aeavalos** [comment]
Gracias
