### ISSUE TITLE
schedule serializable

### ISSUE THREAD

**Issue by FernandoDeDiego** [IIC2413/Syllabus-2018-2#164]
Hola!
En las diapos sale que un schedule es serializable si el grafo de precedencia es acíclico. Me surgió la duda de si la implicancia hacia el otro lado también es cierta, es decir, que si el schedule el serializable, entonces el grafo de precedencia es acíclico.
Saludos!

**Comment by alanezz** [comment]
Hola (voy a contestar igual aunque esté cerrada), esto funciona así:

- Los schedules que tienen el mismo "output" que alguno serial con las mismas acciones son serializables.
- Los schedules que puedo llevarlos a uno serial mediante permutación de acciones no conflictivas se llaman _conflict serializable_. Un schedule de este tipo implica que es serializable. Pero pueden haber schedules serializables que no son conflict serializable.
- El teorema dice que:
> El grafo de precedencia es acíclico **ssi** el schedule es _conflict serializable_.
Si te fijas, es en ambas direcciones pero respecto a schedules que son _conflict serializable_. Si el grafo de precendencia tiene un ciclo no va a ser _conflict serializable_ pero aún puede ser serializable.

Saludos.
