### ISSUE TITLE
Sobre declaración de tablas

### ISSUE THREAD

**Issue by jmopaso** [IIC2413/Syllabus-2018-2#17]
Hola!
Para cuando este estableciendo el dominio de los atributos de una tabla, por ejemplo, en el caso del nombre de un usuario, el tipo de dato lo debo poner como un **varchar** o como **string**? lo pregunto porque si es un varchar aún no tenemos como saber cual será el largo máximo establecido.

**Comment by rfenzo** [comment]
En sqlite todos los varchar en realidad son definidos por detrás como tipo text, y por tanto aunque le coloques varchar(1), de todas formas te dejará colocar un string de largo indefinido. No así en otros como postgresql.
