### ISSUE TITLE
Directorio no encontrado

### ISSUE THREAD

**Issue by Regenschrim** [IIC2413/Syllabus-2018-2#176]
Hola, he seguido los pasos del tutorial para configurar el servidor, pero me pasa que al llegar al paso 6 me tirar error diciendo que el directorio al que intento ingresar no existe, por lo que no puedo crear el archivo. No encontre como resolver el problema, ¿de que forma puedo solucionarlo? Dejo un pantallazo donde se muestra que el directorio no existe.

![image](https://user-images.githubusercontent.com/20805424/49131437-eaad5d80-f2b6-11e8-8a3b-59d0d96cd82f.png)

**Comment by FernandoPieressa** [comment]
Si no esta creado probablemente tendras que crear esa ruta con el comando mkdir de consola

Saludos!

**Comment by Regenschrim** [comment]
Cree los directorios, pero luego me dice que no reconoce el comando nginx. No se cual es el problema, como te digo he hecho todos los pasos al pie de la letra. ¿será que hay algo que debiese estar instalado en el server y no está? Lo único que se me ocurre es que no tenga instalado nginx ya que no reconoce el comando :/

**Comment by Regenschrim** [comment]
ups, creo que me salte eso jaja gracias!!
