### ISSUE TITLE
Pregunta ubicaciones de mensajes en el mapa

### ISSUE THREAD

**Issue by legramsch** [IIC2413/Syllabus-2018-2#178]
Muchos de los mensajes tienen la misma ubicacion, y esto hace que se borren muchos mensajes al sobreponerse 
![image](https://user-images.githubusercontent.com/26261293/49178593-e6bd2200-f32e-11e8-90e6-91413a24a399.png)

¿Es requisitos que se vean todos los mensajes? (cambiandolos todos un poco de lugar, o en su defecto poniendolos en el mismo marcador)

**Comment by alanezz** [comment]
Hola,

No es necesario que se vean todos, puedes agruparlo en marcadores.

Saludos.

**Comment by legramsch** [comment]
Osea tienen que aparecer todos, pero pueden estar agrupados en un marcador?

**Comment by alanezz** [comment]
Puedes hacer lo que se te haga más fácil y escribir en el readme lo que escogiste.
