### ISSUE TITLE
Conexión en Filezilla al nuevo servidor

### ISSUE THREAD

**Issue by jpmoraga1** [IIC2413/Syllabus-2018-2#181]
Hola! Estoy tratando de subir el archivo de la P4 al nuevo servidor por Filezilla, pero no se está realizando la conexión. Me está levantando un error por el tiempo que está tardando en conectarse al server:
![image](https://user-images.githubusercontent.com/24195066/49309728-008b7000-f4bb-11e8-9d8d-986ee00a89bc.png)
Puse el nombre de usuario y contraseña respectivos, por lo que no sé si es algo que estoy haciendo mal o es un error del server.

**Comment by cmp831** [comment]
Pruebalo usando el puerto 22, que es para SFTP en vez de FTP.

**Comment by jpmoraga1** [comment]
Con ese puerto lo tengo. Ahora con mi grupo nos dimos cuenta de que nadie se puede conectar, ni desde putty ni desde filezilla, y yo hace media hora si podía, no se si habremos modificado algo o si se cayó el servidor :(
