### ISSUE TITLE
Duda entrega 1

### ISSUE THREAD

**Issue by frduran** [IIC2413/Syllabus-2018-2#19]
Hola! Aparte de la declaración de tablas y las consultas en álgebra relacional que más se debe hacer para esta entrega? Que se hace con Filezilla y otros?
Saludos!

**Comment by nivek0o0** [comment]
Hola,
para este entrega solamente se pide la declaración de las tablas y las primeras 3 consultas en álgebra relacional. Putty sirve para que los usuarios de Windows se conecten al servidor y puedan ejecutar comandos de consola. Filezilla es el software que ocuparán para subir cada entrega y manipular los archivos de forma interactiva en el servidor. PostgreSQL será el DBMS que ocuparán para la siguiente entrega.
