### ISSUE TITLE
Subir archivo a servidor con FileZilla

### ISSUE THREAD

**Issue by jminostroza** [IIC2413/Syllabus-2018-2#20]
Hola, estaba subiendo mi entrega 1 al servidor, pero quedé  con un par de dudas...

Con eso se supone que ya está arriba mi archivo?
Lo subí en la carpeta correcta?
Falta algo por hacer?

![captura de pantalla 2018-08-23 a la s 12 33 09](https://user-images.githubusercontent.com/26410892/44536287-7a4cda00-a6d2-11e8-9f81-81018b08cee0.jpg)

**Comment by alanezz** [comment]
Hola, con eso estás listo.

Saludos!
