### ISSUE TITLE
Símbolo join

### ISSUE THREAD

**Issue by jmwielandt** [IIC2413/Syllabus-2018-2#21]
Hola, buscando me salen estos simbolos para el join pero no son los de las diapos. ¿Cuál uso y en qué caso? ¿Cuál es el de las diapos?
Gracias.

![image](https://user-images.githubusercontent.com/37153467/44555798-51960600-a70d-11e8-9c58-0fb1db68439a.png)

**Comment by aaossa** [comment]
Hola! Creo que buscas `\bowtie`

![imagen](https://user-images.githubusercontent.com/10425834/44555914-c1a48c00-a70d-11e8-9101-4c6718f24a7b.png)

Es ese?

**Comment by rfenzo** [comment]
En todo caso los que muestras representan a un left outer join, right outer join y full outer join respectivamente

**Comment by jmwielandt** [comment]
Síii!
Muchas gracias! :D
