### ISSUE TITLE
Renombre y joins

### ISSUE THREAD

**Issue by jmwielandt** [IIC2413/Syllabus-2018-2#22]
Hola, quería preguntar cómo funciona en detalle el renombre y el acceso a atributos de resultados de joins en álgebra relacional.

Entiendo que si tengo A(a, b, c) y B(a, b) y hago join(A, B, cond_X) me retorna una relación (A.a, A.b, A.c, B.a, B.b), pero si yo hago renombrar(SuperTabla, join(A, B, cond_X)), ¿cómo es el acceso? Este y otros casos por el estilo, también en relación al producto cruz y si al hacer un join o producto cruz la relación que me retorna queda con un nombre por defecto y cuál es o si eso no pasa.

Gracias.

**EDIT:** otro caso que me causaba dudas es con un join "triple" join(A, join(B, C)), la condición del join externo que hace referencia al resultado del join interno, ¿cómo accede a los atributos? ¿Es 100% necesario un renombre? En caso de hacer un renombre (siendo necesario o no) volvemos a lo de arriba, ¿cómo se accede a esos atributos y qué pasa en caso de tener atributos "repetidos" provenientes de relaciones distintas, pudiendo ser incluso de diferente tipo de dato?

**Comment by alanezz** [comment]
Hola, respecto a la primera pregunta, para evitar ambigüedades, deberías renombrar los atributos antes de hacer el join.
Respecto a la segunda, puedes seguir accediendo como B.atributo o C.atributo. Aunque siempre puedes renombrar los atributos antes hacer el join.
