### ISSUE TITLE
Sobre primera consulta

### ISSUE THREAD

**Issue by legramsch** [IIC2413/Syllabus-2018-2#24]
Hola, en esta consulta:

> 1. Dado el nombre de un usuario, indique todas las tiendas donde ha comprado

¿Se asume que no van a haber dos nombres iguales? O si hay dos nombres iguales debería mostrar de ambos usuarios?

**Comment by rfenzo** [comment]
Mira la issue #5

**Comment by legramsch** [comment]
Ups, gracias
