### ISSUE TITLE
Contraseña servidor (no tenemos acceso) [SOS]!

### ISSUE THREAD

**Issue by jmwielandt** [IIC2413/Syllabus-2018-2#26]
[GRUPO 39]
Hola, intentando entrar al servidor la clave que puso mi compañero ya no funciona (a ambos nos dice "acceso denegado"). La original, "grupo39", tampoco.
¿Reiniciaron las contraseñas y por defecto es otra? ¿Alguien se metió en nuestro server y cambió la contraseña?

Gracias.

**Comment by FernandoPieressa** [comment]
Hola!

El servidor está cerrado aún, lo abriré durante la tarde.

**Comment by jmwielandt** [comment]
Ah ._.
No sabía que no iba a estar siempre abierto. Entonces hay horarios especiales en los que estará abierto o cómo funciona? 😮

**Comment by FernandoPieressa** [comment]
Entre entregas los servidores se encontrarán cerrados

Saludos!
