### ISSUE TITLE
codificacion casen.db

### ISSUE THREAD

**Issue by gtquiroga** [IIC2413/Syllabus-2018-2#28]
Al abrir casen.db me aparecen los atributos en bytes, sin decodificar.

mujeres int,
total int,
e0a4 int,
e5a9 int,

como arreglo esto?

**Comment by alanezz** [comment]
Hola, no son atributos sin decodificar. e0a4 corresponde a personas con edad de 0 a 4 años. Esto está en la aclaración del enunciado.

Saludos.
