### ISSUE TITLE
Formato fechas en bases de entrega 2

### ISSUE THREAD

**Issue by rihanuch** [IIC2413/Syllabus-2018-2#29]
Hola!

Quería saber si podemos modificar las bases de datos para que las fechas tengan un formato adecuado y así podamos trabajar con ellas. De ser así, debemos subir el código que modifica las bases o simplemente las bases modificadas?

Gracias!

**Comment by alanezz** [comment]
Hola,

Sí, pueden hacer esa modificación. No es necesario subir el código con el que procesan las bases de datos. Lo importante es que el resultado de las consultas sea consistente con los datos que les dimos.

Saludos.

**Comment by rihanuch** [comment]
Gracias!
