### ISSUE TITLE
Columna id_usuarios2 de usuariosPagos.csv

### ISSUE THREAD

**Issue by nachocontreras** [IIC2413/Syllabus-2018-2#30]
Hola!

El problema es que id_usuario2 no hace referencia a un usuario, porque llega a más de 160 y hay 118 usuarios. Por lo que se estaria haciendo referencia a una cuota, que a su vez esta haciendo referencia a un pago, es decir, referencia circular.

Entonces, ¿Está bien la columna id_usuario2 de la forma en que está en el archivo?

**Comment by FernandoPieressa** [comment]
Hola! 

Efectivamente, le faltaban columnas a esa tabla, ahora se arregló

Saludos!
