### ISSUE TITLE
materia i1

### ISSUE THREAD

**Issue by jpsiegel** [IIC2413/Syllabus-2018-2#34]
Dado que ni en la guia ni en ninguna de las i1 anteriores se pregunta dependendia/BCNF/3NF, queria saber si entran estas materias en nuestra i1.
Saludos

**Comment by alanezz** [comment]
Hola,

Esto entra en la I1. Como mencioné en la última clase, en la carpeta actividades dejé el enunciado de una actividad que te va a servir para estudiar esta materia en la prueba. El lunes vamos a comentar la respuesta al ejercicio.

Saludos.
