### ISSUE TITLE
Archivo servicioscompra.csv  Proyecto

### ISSUE THREAD

**Issue by emeiese** [IIC2413/Syllabus-2018-2#35]
Hola! 
En el archivo servicioscompra.csv están las siguientes columnas:

servicioscompra.csv | id_servicio | nombre | precio | descripcion | id_servicio | id_servicio1

No me queda claro, primero, por qué se repite el id_servicio, pero asumo que es un error y que sólo es correcto poner una de sas columnas. Por otro lado, no me queda claro qué significaría id_servicio1 en este caso. 

Gracias.

**Comment by stephichau** [comment]
hola!

`id_servicio1` debería ser `id_compraservicio` :)
