### ISSUE TITLE
Consulta uso ORDER BY en GROUP BY

### ISSUE THREAD

**Issue by aeavalos** [IIC2413/Syllabus-2018-2#38]
Para una consulta donde quiero ordenar ciertos datos en base a un promedio que voy a sacar de un GROUP BY, es correcto usar el ORDER BY así?

SELECT C.descripcion, SUM(P.cantidad)
FROM Productos AS C, Pedidos AS P
WHERE C.pid = P.pid
GROUP BY C.pid
ORDER BY SUM(P.cantidad)

O es legal hacer:
SELECT C.descripcion, SUM(P.cantidad) AS Suma
FROM Productos AS C, Pedidos AS P
WHERE C.pid = P.pid
GROUP BY C.pid
ORDER BY Suma

Desde ya muchas gracias 😄

**Comment by rfenzo** [comment]
Hola!

Dependerá únicamente del motor de bases de datos que utilices, hay en algunos en los que la segunda consulta que indicas no funcionará mientras que la primera si.

En este curso se utiliza PostgreSQL y por tanto debes buscar/probar si aplica en este caso.

Por lo que pude encontrar [aquí](https://www.postgresql.org/message-id/271d057bf6acfee775e7c47fe899cc9e%40biglumber.com), sí es válido utilizar la suma renombrada como parámetro del ORDER BY, pero debo decir que no lo he probado.
