### ISSUE TITLE
UNION vs UNION ALL

### ISSUE THREAD

**Issue by naquiroz** [IIC2413/Syllabus-2018-2#39]
No me queda clara la diferencia entre `UNION` y `UNION ALL`

Quiero saber si lo entendí bien.

Ejemplo, si yo tengo una tabla de `Actores` y otra de `Peliculas` y uno los nombres, y aparece una pelicula "Gloria" y un actor "Gloria"

### Con `UNION`
Aparecería "Gloria" una sola vez

### Con `UNION ALL`
Aparecería "Gloria" dos veces (una vez por tabla)

Lo entendí bien?

:v:  Gracias :blush:

**Comment by alanezz** [comment]
Hola,

Lo entendiste bien 👌 

Saludos.
