### ISSUE TITLE
Sobre atributos extra y Consultas

### ISSUE THREAD

**Issue by emeiese** [IIC2413/Syllabus-2018-2#4]
Hola! Me interesa saber si es qué cuenta exactamente como 'atributo extra'. Si agrego un atributo 'hola1' a una relacion X, y luego agrego este mismo atributo a la relación Y, ¿esto cuenta como haber agregado 2? ¿o cuenta como uno solo?

Por otro lado, en el enunciado sólo dice que hay que pasar a algebra relacional las consultas 1, 2 y 3, pero    también me gustaría saber qué hay que hacer con las consultas 4, 5 y 6. ¿Simplemente verificar que las consultas se podrían hacer con el esquema planteado? ¿No hay que justificar escribiéndolas en SQL o subiendo alguna base de datos o algo así? 

Por útimo, y es sólo para confirmar: 
una declaración del esquema es simplemente subir algo de la forma: 
- R0(at01, at02)
- R1(at11, at12, ..., at 1n)
¿cierto?

Desde ya, muchas gracias!

**Comment by alanezz** [comment]
Hola,

1) Si agregas un atributo hola1 a dos relaciones distintas, y tiene sentido, está bien y cuenta como dos.
2) Tienes que hacer un esquema y pensar si puedes responder las consultas 4, 5  y 6. Estas probablemente se pidan en SQL en el futuro.
3) Esa declaración de esquema está correcta, aunque tienes que añadir los tipos, y deseablemente, la llave primaria.

Saludos!
