### ISSUE TITLE
Por qué estaba incompleto?

### ISSUE THREAD

**Issue by naquiroz** [IIC2413/Syllabus-2018-2#40]
Hola, se que vimos esto en clases (de hecho fuí :sweat_smile: ) pero aun así no recuerdo ni entiendo porque estaba incompleto lo siguiente.

![image](https://user-images.githubusercontent.com/29825816/45395990-32eda580-b60f-11e8-91db-563cbf1a50b4.png)
 Cual era la razón?

Saludos.

**Comment by alanezz** [comment]
Porque eso me dice que la Película, la Boleta y la Persona me determinan el Local de Videos. No hay forma de escribir que solamente la boleta me implica el Local. Si le das una vuelta, la relación que vincula 4 entidades está un poco sobre cargada, y podríamos modelar mejor el problema.

Saludos!

**Comment by naquiroz** [comment]
Gracias @alanezz !
