### ISSUE TITLE
Proyecto - Duda DB Grupo Impar

### ISSUE THREAD

**Issue by bimartinez** [IIC2413/Syllabus-2018-2#42]
Hola!

Junto con mi compañero estábamos revisando la base de datos de las transacciones (`usuarioPagos.csv`) y tenemos la duda de como obtener las fechas de aquellas transacciones que no son hechas en cuotas. Estas no aparecen en el archivo `Cuotas.csv` que es de donde estamos obteniendo las fechas aquellas transacciones que si aparecen ahí.

Saludos!

**Comment by stephichau** [comment]
Hola!

Hay muchas formas de modelar este problema de tal manera de que no les falten más datos. Entonces, si creen que faltan, intenten modelarlo de otra forma :).

Saludos!

**Comment by bimartinez** [comment]
Gracias por tu respuesta, pero el problema es el siguiente, hay transacciones en que la única referencia es en el archivo `usuariosPagos.csv` (por ejemplo la transaccion que tiene `id_pagos = 8` no tiene referencia en ningún otro archivo de la base de datos), y no hay ninguna relación con fechas en ese caso (fechas que nos piden para la primera consulta). 

Saludos!

**Comment by FernandoPieressa** [comment]
El problema fue arreglado, ahora todas las transacciones tienen mas de una referencia
