### ISSUE TITLE
Acceder proyecto navegador

### ISSUE THREAD

**Issue by jmwielandt** [IIC2413/Syllabus-2018-2#43]
Hola, estoy intentando acceder a la página del proyecto de mi grupo desde el navegador pero no sé cómo.
Filezilla me copia esta url al portapapeles [sftp://grupo39@bases.ing.puc.cl/home/grupo39/Sites/index.html](sftp://grupo39@bases.ing.puc.cl/home/grupo39/Sites/index.html) y no funciona :(
Intenté cambiar el sftp por http y me sale esto: 
![image](https://user-images.githubusercontent.com/37153467/45571949-5185b380-b83e-11e8-90c8-fe0af521d3fd.png)

**Comment by nivek0o0** [comment]
Hola, la dirección donde está tu homepage es http://bases.ing.puc.cl/~grupo39/.

**Comment by jmwielandt** [comment]
Muchas gracias! :D
