### ISSUE TITLE
Información de Usuarios - Grupo Impar

### ISSUE THREAD

**Issue by leolivares** [IIC2413/Syllabus-2018-2#45]
Para la consulta 2, nos piden el usuario por cada abono.
Sin embargo existen ids de usuarios, por ejemplo el 20, que realizaron un abono pero no se tiene información de ellos (como nombre, apellido, etc).
Ignoramos estos casos y entregamos solo los que podamos mostrar sus nombres?
Gracias.

**Comment by FernandoPieressa** [comment]
Hola! Es verdad lo que dices, no hay esa información para grupo impar. Tienes dos opciones:

1) Puedes agarrar la base de datos de usuarios del grupo par para sacar los nombres que te faltan (si, comparten usuarios)

2) Entregar solamente el id para los usuarios que no tienes el nombre.

Saludos!

**Comment by leolivares** [comment]
@FernandoPieressa Gracias!
