### ISSUE TITLE
Fechas de Transacciones - Grupo Impar

### ISSUE THREAD

**Issue by leolivares** [IIC2413/Syllabus-2018-2#46]
Para la consulta 1, nos piden las transacciones realizadas en una fecha en específico.
Sin embargo, como se mencionó en la issue #42, solo contamos con fechas de expiración para las transacciones por cuotas.
Me queda la duda si faltan datos. Muchas gracias.

**Comment by FernandoPieressa** [comment]
El problema fue arreglado, revisa la otra issue
