### ISSUE TITLE
Precios con "$"

### ISSUE THREAD

**Issue by llloyola** [IIC2413/Syllabus-2018-2#47]
Hola! Noté que en las bases de datos los precios vienen de la forma "$xxx.xxx,xx" y me está generando unos problemas el signo $.
Recomiendan alguna forma de poder importar los csv a sqlite para trabajar los precios como int o debemos simplemente alterar, de alguna forma, todos los precios de la base de datos? 
Gracias de antemano y espero hayan tenido felices fiestas 🇨🇱😄

**Comment by FernandoPieressa** [comment]
Hola!

Pueden alterar sin problemas el tipo de dato de las columnas en el csv para que lo puedan trabajar como desean.

Saludos!
