### ISSUE TITLE
Header duplicado tiendaProductoTienda

### ISSUE THREAD

**Issue by emeiese** [IIC2413/Syllabus-2018-2#48]
hola! Para los grupos pares, hay un archivo con nombre tiendaProductoTienda que lleva duplicado el id_tienda, es un error simplemente, o se espera que nosotros hagamos algo con eso?

**Comment by FernandoPieressa** [comment]
Hola!

De las bases de datos que les entregamos basta que usen los datos que encuentren necesarios para las consultas solicitadas, por lo que si no necesitan un atributo, lo pueden ignorar
