### ISSUE TITLE
Problemas con el Servidor

### ISSUE THREAD

**Issue by leolivares** [IIC2413/Syllabus-2018-2#49]
Hola.
Creo que el servidor no esta funcionando. Desde el martes no logro acceder a nuestra página del proyecto, y tampoco por medio de FileZilla.
Gracias.

**Comment by FernandoPieressa** [comment]
Efectivamente no esta funcionando, probablemente fue apagado por el encargado de los servidores del departamento de computación por estas fechas. Mañana aprovechare a preguntar que sucedio.

Saludos
