### ISSUE TITLE
Consulta 1: nombre de un usuario

### ISSUE THREAD

**Issue by Mariana-Ortega-del-Rio** [IIC2413/Syllabus-2018-2#5]
En la consulta 1 se pide buscar dado el "nombre de un usuario". Anteriormente en los requerimientos de Usuario se coloca que cada usuario tiene un identificador único y además un nombre, etc.
Entonces,¿ "nombre de un usuario" se refiere a ese identificador único o al nombre? (Si se refiere solo al nombre estos podrían estar repetidos).

Saludos!!Y gracias de antemano :)

**Comment by alanezz** [comment]
Hola,

Nombre del usuario se refiere al nombre, da lo mismo que puedan estar repetidos. Piensa cuando buscas alguna entidad en un buscador. Generalmente nos referimos a ella por el nombre y no por el id.

Saludos!
