### ISSUE TITLE
Edades Usuarios Par

### ISSUE THREAD

**Issue by beayancan** [IIC2413/Syllabus-2018-2#50]
En el enunciado se especifica que la base de datos debe contener la información de los usuarios entre los que se incluye la edad y su dirección. Sin embargo, en la base de datos de usuarios que se nos dan estos atributos no son incluidos ¿Debemos simplemente ignorarlos?

**Comment by stephichau** [comment]
Hola!

Actualizamos el archivo Usuarios.csv con las edades :)
