### ISSUE TITLE
Consulta NebStore SQL

### ISSUE THREAD

**Issue by Cschavez** [IIC2413/Syllabus-2018-2#52]
Hola!
La primera consulta para los que tenemos NebStore dice: "Dado el nombre de un usuario, indique todas las tiendas donde ha comprado". Está bien que sea el nombre del usuario? a lo que voy es que podrían haber usuarios con el mismo nombre, entonces estaríamos considerando las tiendas donde han comprado todos los usuarios con el mismo nombre. Gracias!

**Comment by alanezz** [comment]
Sí, está correcto. Puede ser que para cierto nombre vienen tiendas donde compraron usuarios distintos. De todas formas, cuando muestres la respuesta, puedes mostrar la tienda junto al id del usuario si lo quieres hacer más limpio.

Saludos.
