### ISSUE TITLE
Informacion Seguros - Enunciado Impar

### ISSUE THREAD

**Issue by MarceloSaldias** [IIC2413/Syllabus-2018-2#53]
Hola! 

En el enunciado de la Entrega 1 se menciona que los seguros tienen una fecha de contratacion, expiracion y un tipo. Sin embargo, estos datos no se encuentran en los csv :cry:

Soy yo el perdido o faltan estos datos ?

**Comment by alanezz** [comment]
Hola, para esta entrega basta que la tabla de seguros se vea como el csv subido. Pueden omitir las otras columnas porque no son necesarias en ninguna consulta.

Saludos.
