### ISSUE TITLE
Usuarios - Impar

### ISSUE THREAD

**Issue by nicoparraguez** [IIC2413/Syllabus-2018-2#54]
hola, tengo una duda acerca de los usuarios ya que con las tablas entregadas podemos hacer una tabla usuarios con sus nombres,ids,apellidos etc , el problema es que hay usuarios que no han generado ningun pago pero si han generado abonos el tema es que no hay forma de obtener desde abonos su nombre,apellido etc.. 

Esta bien si no tomo en cuenta los usuarios que aún han hecho pagos o debo agregarlos sin nombre ni demases datos

**Comment by FernandoPieressa** [comment]
Hola. Puedes hacer lo mismo que en #45
