### ISSUE TITLE
Fechas transacciones v/s fechas expiración [IMPAR]

### ISSUE THREAD

**Issue by Taeval** [IIC2413/Syllabus-2018-2#55]
En las consultas que nos piden hacer, necesitamos las fechas en las que fueron realizadas las transacciones, sin embargo el archivo usuariosPagos.csv no tiene fechas. El archivo Cuotas.csv tiene fechas, pero de expiración. El archivo tarjetasAbono.csv tiene fechas, pero estos son abonos, no transacciones/pagos entre usuarios. 

Se que esto fue tratado en las issues #42 y #46 y se mencionó que el problema fue solucionado y que se agregaron más referencias, mi duda en particular es si es válido usar la fecha de expiración de las cuotas como fecha para la consulta 1 que se nos pide realizar.

**Comment by stephichau** [comment]
hola!
Le agregamos una columna al archivo usuariosPagos :)
