### ISSUE TITLE
Datos para abrir base de datos en servidor

### ISSUE THREAD

**Issue by aeavalos** [IIC2413/Syllabus-2018-2#56]
En los archivos que subieron de la ayudantía, sale que para acceder a la base de datos se necesita: Host, User, Port, Password y Database.
Al usarlo para abrir nuestra base de datos:
- Host sería igual "localhost"
- User nuestro grupo
- Password nuestro grupo
- Database el nombre de nuestra base de datos (sin .db?)

Eso estaría correcto?
Y "Port" qué es? O era para la base de datos específica de la ayudantía?

**Comment by FernandoPieressa** [comment]
Lo que dijiste esta correcto.

Para puerto pueden usar cualquiera que este libre, o como sale en ayudantía, 5432

saludos!

**Comment by aeavalos** [comment]
Muchas gracias 😄

**Comment by aeavalos** [comment]
Cuando prueba la página, me sale el siguiente error: 

"SQLSTATE[08006] [7] FATAL: database "Nebstore" does not exist"
Por qué no encuentra la base de datos? Debo ponerla en otra carpeta diferente de Sites? 🤔 

Desde ya muchas gracias 😄

**Comment by alanezz** [comment]
Hola,

Estás intentando mover un .db de SQLite al servidor? Esto no te va a funcionar. Lo que se tiene que hacer acá es ingresar a postgres en el servidor y luego crear una base de datos (en este caso con el nombre Nebstore). Luego ahí tienes que crear las tablas por la terminal.

Saludos.

**Comment by aeavalos** [comment]
Si, eso estaba haciendo. Y ¿Como abro postgres en el servidor?

**Comment by alanezz** [comment]
Cuando estás conectado via ssh con el servidor debes escribir `psql grupo<numgrupo>`. La password es `grupo<numgrupo>`. Ojo que cuando reemplaces tu número de grupo no debes escribir los <>.

Saludos.

**Comment by aeavalos** [comment]
al escribir psql grupo<numero> se abre una base de datos con nombre grupo<numero> o ahora debo crear la base de datos que yo quiero?

**Comment by alanezz** [comment]
No, tú te estás conectando a la base de datos de tu grupo, que sería grupoXX. En esa base de datos tienes que crear tus tablas y todo lo demás. Después con PHP accedes a esa base de datos.

**Comment by aeavalos** [comment]
Y una vez que las tengo creadas, como logro importar los datos de los .csv? He intentado con:

COPY Usuarios FROM 'sftp://grupo4@bases.ing.puc.cl/home/grupo4/Usuarios.csv' DELIMITER ',' CSV;

Pero me dice que tengo que ser superuser para usar COPY, y me recomienda \copy, pero no he encontrado la documentación de como usar ese comando.

**Comment by alanezz** [comment]
Hola,

Se ocupa de la misma forma, pero el detalle son los permisos que usa. La segunda [respuesta](https://stackoverflow.com/questions/28602647/postgresql-csv-import-from-command-line) de stackoverflow en esta pregunta lo explica.

Saludos.

**Comment by nfbalbontin** [comment]
Hola, qué tal? 
Con respecto a esto mismo, siguiendo los pasos anteriores finalmente coloco: 
'sftp://grupo7@bases.ing.puc.cl/home/grupo7/archivos/usuariosPagos.csv'
pero me indica que no existe dicho archivo o directorio. ¿Sabrán a qué se debe esto? 
Saludos!

**Comment by nfbalbontin** [comment]
Hola, qué tal?
Con respecto a esto mismo, siguiendo los pasos anteriores finalmente coloco:
\copy usuariosPagos from 'sftp://grupo7@bases.ing.puc.cl/home/grupo7/usuariosPagos.csv' delimiter ',' header
pero me indica que en 
'sftp://grupo7@bases.ing.puc.cl/home/grupo7/usuariosPagos.csv' 
no existe dicho archivo o directorio. ¿Sabrán a qué se debe esto?
Saludos!

**Comment by CmPoblete** [comment]
Pon esto : \copy usuariosPagos from '/home/grupo7/usuariosPagos.csv' delimiter ',' header

**Comment by nfbalbontin** [comment]
Lo hice, y me retorna el mismo error :(

**Comment by CmPoblete** [comment]
seguro que usuariosPagos.csv esta en esa direccion? A mi me funciono con eso

**Comment by nfbalbontin** [comment]
<img width="933" alt="captura de pantalla 2018-09-25 a la s 17 07 27" src="https://user-images.githubusercontent.com/26261777/46039982-82d76c80-c0e5-11e8-9f71-651ac54d07a4.png">

**Comment by CmPoblete** [comment]
Entonces tiene que ser asi: \copy usuariosPagos from '/home/grupo7/archivos/usuariosPagos.csv' delimiter ',' header

**Comment by alanezz** [comment]
Hola, según lo que muestras ahí el archivo está en `archivos/usuarios pagos.csv`. Te falta agregar el directorio archivos en tu ruta.

**Comment by nfbalbontin** [comment]
si, disculpa, se me había olvidado anotarlo en la issue pero si lo hice en el programa 😅
Al final, esto es lo que ingreso: 
\copy usuariosPagos from 'sftp://grupo7@bases.ing.puc.cl/home/grupo7/archivos/usuariosPagos.csv' delimiter ',' header

**Comment by nfbalbontin** [comment]
<img width="867" alt="captura de pantalla 2018-09-25 a la s 17 16 02" src="https://user-images.githubusercontent.com/26261777/46040449-b49d0300-c0e6-11e8-9709-ef0d4ae476a3.png">
Extra spam por si las dudas

**Comment by CmPoblete** [comment]
quitale el sftp://grupo7@bases.ing.puc.cl

**Comment by nfbalbontin** [comment]
jajajaja ahí me funcionó. Gracias
