### ISSUE TITLE
Uso de Vistas en PHP

### ISSUE THREAD

**Issue by aeavalos** [IIC2413/Syllabus-2018-2#57]
Si para una consulta utilizamos vistas, las ingresamos a php al igual que las consultas? O debemos ponerlas de alguna forma especial?

**Comment by FernandoPieressa** [comment]
Algo de este estilo buscamos:

http://bases.ing.puc.cl/~ayudantia/AyudantiaPHP/index.php

**Comment by aeavalos** [comment]
me refiero a que si para la creación de una consulta en SQL, utilizamos un "CREATE VIEW", como implementamos eso dentro de la consulta que realiza PHP dentro del código de la página.

**Comment by alanezz** [comment]
Lo que quieres es algo como lo que hacen [acá](https://stackoverflow.com/questions/7689715/calling-mysql-create-view-using-php-code).

**Comment by aeavalos** [comment]
Si, muchas gracias 😄
