### ISSUE TITLE
Correr ejemplo ayudantía

### ISSUE THREAD

**Issue by akrebs2** [IIC2413/Syllabus-2018-2#58]
Hola.

¿Cómo puedo correr en mi computador el ejemplo visto en ayudantía, luego de que ya está en mi computador?

¿Qué pasos se deben seguir?

Estoy medio complicado con el tema. Gracias

**Comment by benjadb** [comment]
Yo también ando complicado con eso, en mi caso, no tengo ninguna experiencia con aplicaciones web. Gracias

**Comment by cmp831** [comment]
Les sugiero Les sugiero no instalar PHP en su propio computador porque es algo complicado. Por eso está el servidor que le otorgamos, para que puedan correr el código sin instalar PHP en su computador. Para correr el código suban los archivos PHP que han creado en las carpetas Sites de su grupo, y podrán accederlas en el link correspondiente http://bases.ing.puc.cl/~grupoXX/nombre_del_archivo.php

**Comment by alanezz** [comment]
Como dice Wenyi, el ejemplo de la ayudantía no lo deberían correr en su computador, sino que deben subir los archivos php al servidor. Luego ingresan al sitio que se señaló anteriormente para ver cómo está funcionando todo. Tienen que tener ojo con ingresar correctamente los parámetros de la configuración de la db.

Saludos.
