### ISSUE TITLE
Abonos primary key

### ISSUE THREAD

**Issue by cataherrera** [IIC2413/Syllabus-2018-2#59]
Hola que para la tarea impar si necesito hacer una tabla abonos con fechar, cantidad, valor_netcoin, y id_tarjeta no hay ningun elemento o combinacion que sea unico, debo hacer una columna extra id? o no podemos agregar mas datos de los que estan en la tabla?

**Comment by alanezz** [comment]
Sí pueden. En este caso recomendaría agregar un id como llave primaria.

Saludos.

**Comment by cataherrera** [comment]
o podria asumir que solo hay un abono por fecha?

**Comment by alanezz** [comment]
No, porque eventualmente puedes hacer dos abonos en la misma fecha.
