### ISSUE TITLE
Entrega 1 – Grupo Impar – Consulta 2

### ISSUE THREAD

**Issue by ifieldhouse** [IIC2413/Syllabus-2018-2#6]
En la consulta 2 dice que debo dar el nombre de la persona que pagó y el nombre de la tienda, pero no existe ninguna tabla `Tienda` o similar. ¿El nombre estaría dentro del `comentario` de `Transacción`? ¿o la tienda cuenta como un `Usuario`?

**Comment by alanezz** [comment]
Hola,

En realidad me estaba refiriendo al usuario de destino, que debería ser una cuenta que representa a alguna tienda.

Saludos!

**Comment by ifieldhouse** [comment]
Gracias!
