### ISSUE TITLE
[PAR] Mostrar **TODO** acerca de la compra más cara

### ISSUE THREAD

**Issue by TamaraCucumides** [IIC2413/Syllabus-2018-2#60]
Hola,
cuando se pide mostrar "todo" acerca de una transacción se refiere literalmente a todo, i.e: el id, nombre, edad, apellido de quien compro más TODA la informacion de la tienda donde se compro más TODA la informacion de los articulos comprados, etc?

Puedo mostrar las cosas más relevantes, como el id del usuario (o nombre), id de la tienda (o nombre), la fecha, el monto total gastado y el id de la compra? 

Gracias de antemano!

**Comment by alanezz** [comment]
Hola, puedes mostrar solamente el id del usuario (o nombre), id de la tienda (o nombre), la fecha, el monto total gastado y el id de la compra.

Saludos!

**Comment by TamaraCucumides** [comment]
Gracias!!!
