### ISSUE TITLE
Extension de vscode

### ISSUE THREAD

**Issue by pahaeussler** [IIC2413/Syllabus-2018-2#61]
Hola, me acuerdo que en la ayudantía, se utilizó una extensión de vscode para poder correr la página web del proyecto con tan solo guardar. Me gustaría hacer lo mismo, cual es la extensión y la configuración.
Gracias

**Comment by cmp831** [comment]
Hola, el plugin que se usó fue [sftp](https://marketplace.visualstudio.com/items?itemName=liximomo.sftp), lo puedes buscar directamente en el marketplace dentro de VsCode e instalarlo directamente. Recuérdate de apretar el botón reload en la página del plugin una vez instalada. Luego, puedes abrir la carpeta donde están tus códigos, y usar la tecla `ctrl+shift+p` para abrir la línea de comando de VsCode. 

Para configurarlo, debes tipear `SFTP: config` y correrlo, para editar el archivo de configuración. 

Un ejemplo será:
```
{  
    "protocol": "sftp",  
    "host": "bases.ing.puc.cl",  
    "port": 22,  
    "username": "NOMBRE_DE_USUARIO",  
    "remotePath": "/home/NOMBRE_DE_USUARIO/Sites"  
}
```
Debes cambiar el NOMBRE_DE_USUARIO a su nombre de usuario del servidor (`grupoXX`).
Una vez configurado, ya puedes usar el plugin abriendo la línea de comando usando `ctrl+shift+p,` y si quieres subir el archivo PHP que tienes abierto en la ventana de VsCode, puedes usar el comando `SFTP: Upload Active File` . 

También existen otros [comandos útiles](https://github.com/liximomo/vscode-sftp#main-commands), puedes probarlas para ver cual te sirve más.

**Comment by pahaeussler** [comment]
Gracias! me funciono perfecto.
