### ISSUE TITLE
Servicio Grupo Par

### ISSUE THREAD

**Issue by pahaeussler** [IIC2413/Syllabus-2018-2#62]
Estuvimos revisando las bases de dato y en TiendaServicioProducto.csv se hace referencia al id_servicio 1, sin embargo en ServicioCompra.csv no se encuentra ese id_servicio.

**Comment by alanezz** [comment]
Eso pasa porque nadie ha comprado ese Servicio. Para esta entrega puedes omitir esos productos/servicios.

Saludos.

**Comment by pahaeussler** [comment]
Es raro, porque una tienda vende un Servicio que no existe. Voy a eliminar ese dato.

**Comment by alanezz** [comment]
Nuevamente, más que el hecho que no exista, nadie lo ha comprado, por lo que por esta entrega es mejor omitirlo.

Saludos.
