### ISSUE TITLE
[Pares] Distintos servicios/productos por compra

### ISSUE THREAD

**Issue by fedetaladriz** [IIC2413/Syllabus-2018-2#63]
Hola!
En el enunciado se menciona que se pueden tener distintos productos o servicios (según corresponda) por cada compra. Sin embargo, en la bdd que nos entregaron, en el archivo ProdcutoCompraProducto, por cada id_compra, se tiene un solo id_producto y su respectiva cantidad. Por qué solo hay un producto por compra? Lo mismo para los servicios en el archivo servicioscompra. 
Gracias!

**Comment by alanezz** [comment]
El modelo tiene que ser para lo que se menciona en el enunciado, a pesar de que en este caso no haya una compra con varios productos distintos en ella.

**Comment by PIPEAPABLAZA** [comment]
no me hace sentido esto :/ ... porque estaríamos haciendo un modelo que no corresponde a la información que tenemos, ni a las consultas que haremos.

**Comment by alanezz** [comment]
Porque en la modelación pedimos que cada compra pueda tener uno o más productos distintos en cualquier cantidad cada uno. En esto caso, cada compra tiene un solo producto distinto en cierta cantidad. El modelo solicitado calza con lo que te entregamos. La consulta en este modelo (la compra más cara) también se puede responder. En la siguiente entrega cada compra va a tener más de un producto distinto.

De todas formas no estás obligado a nada en particular, mientras tu modelo esté en BCNF y la respuesta a las consultas sea correcta.

Saludos.
