### ISSUE TITLE
Problema para realizar conexión en sitio web

### ISSUE THREAD

**Issue by antoniacobo** [IIC2413/Syllabus-2018-2#66]
Hola! Estoy tratando de hacer la conexión según lo que hicieron en la ayudantía de PHP. Hice un archivo llamado `data_grupo.php`, otro `conexion.php` iguales a los de la ayudantía, pero cambiando mis datos de grupo y la ubicación del archivo `data_grupo.php`. También cambié el puerto en caso de que el que usaron en la ayudantía esté ocupado (del 5432 al 8000). Según yo, lo que he hecho es coherente. Pero cuando trato de entrar me sale el siguiente error.

`'PDOException' with message 'SQLSTATE[08006] [7] could not connect to server: Connection refused Is the server running on host "localhost" (::1) and accepting TCP/IP connections on port 8000? could not connect to server: Connection refused Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 8000?' in /home/grupo31/Sites/conexion.php:5 Stack trace: #0 /home/grupo31/Sites/conexion.php(5): PDO->__construct('pgsql:dbname=gr...') #1 /home/grupo31/Sites/test_consulta.php(13): include_once('/home/grupo31/S...') #2`

¿Alguna sugerencia?

**Comment by alanezz** [comment]
Puedes pegar aquí lo que tiene el archivo conexión? De todas formas, el puerto es el 5432.

**Comment by naquiroz** [comment]
@antoniacobo ya lo solucioné :sweat_smile:

**Comment by alanezz** [comment]
Qué era?

**Comment by naquiroz** [comment]
En el archivo `ejemplo_consulta.php` (_renderea_ la consulta en tabla) faltaba 

```php
  <?php
  include_once "psql-config.php"; # Esta linea
?>
