### ISSUE TITLE
Algunas aclaraciones respecto a lo que se espera en la entrega

### ISSUE THREAD

**Issue by alanezz** [IIC2413/Syllabus-2018-2#67]
Estimados, subo esta issue para aclarar un par de aclaraciones del proyecto en base a las preguntas frecuentes para quienes se sientan muy confundidos.

### ¿Qué tengo que hacer?

1. En esta entrega en concreto hay que desarrollar una aplicación web en php muy sencilla, que sirva de interfaz para hacer las consultas que a cada grupo le corresponda. Cada grupo tiene un usuario en el servidor al que acceden por `ssh` (quienes tienen windows tienen que usar putty para conectarse al servidor). 
2. Una vez dentro del servidor pueden acceder a la base de datos en PostgreSQL de su grupo. Para acceder deben escribir `psql grupo<numgrupo>`. La password es `grupo<numgrupo>`. Recuerden que cuando reemplacen el número de grupo no deben escribir los `<>`. Ojo que cuando usan PostgreSQL **no se genera un archivo .db**, esto es exclusivo de SQLite3.
3. Deben mover los archivos .php (y .html si tienen) desde su computador a Filezilla. Los .php **no tienen que correrlos en su computador**, sino que se van probando directamente en línea. Luego deberían ingresar a http://bases.ing.puc.cl/~grupoXX/nombre_del_archivo.php para ver en línea su página.
4. Desde los .php deben hacer las consultas a su base de datos. Las respuestas a las consultas también se deben mostrar en línea. Comúnmente. se despliegan como tabla de html.

### ¿Qué pasa si ya cargué los datos en SQLite?

Como dije anteriormente, los .db no se leen en PostgreSQL, pero lo que pueden hacer es exportar sus tablas en .csv para moverlas al servidor y luego cargarlas en PostgreSQL. En cuanto a las consultas, deberían ser las mismas en PostgreSQL y SQLite pero hay un detalle: cuando en SQLite hay una consulta con agregación podemos proyectar atributos que no están en el `GROUP BY` (que es algo que no hace mucho sentido). Esto tira error en PostgreSQL.

### ¿Cómo cargo los datos en PostgreSQL y me conecto a la base de datos?

1. Para cargar los datos tienen que usar el comando `\copy`, que funciona igual que el comando `copy` pero no requiere de permisos de superusuario. Ayer subí este [post](https://stackoverflow.com/questions/28602647/postgresql-csv-import-from-command-line) de StackOverflow que explica un poco lo que pasa. Pueden ver más en la documentación de PostgreSQL.
2. Los datos para conectarse son:

- `HOST`: `localhost` 
- `USER`, `PASSWORTD`, `DATABASE`: `grupoXX` 
- `PORT`: 5432

### ¿Qué pasa si sólo entrego el informe?

En esta entrega lo importante es hacer las consultas pero en un entorno realista. Si no tienen una página web no vamos a probar sus consultas, por lo que no tendrían el puntaje asignado a la página web y una parte muy baja del puntaje de las consultas SQL. Recordemos que en el enunciado se señala que la nota de las consultas depende de la correctitud de las mismas cuando se prueben en su aplicación.

### No sé por donde partir

Lo primero es entender y hacer correr el ejemplo de la ayudantía. Les recomiendo subirla, cambiar los datos de la conexión y jugar con tablas que vayan creando por la terminal en PostgreSQL. Luego la entregan la empiezan a construir desde ahí.

Nuevamente quiero recalcar que esta entrega si bien no es complicada, requiere tiempo. Si lo dejan para último momento no les va a ir bien. Aprovechen los días extra que les di.

Saludos.

**Comment by valerojasm** [comment]
Hola! Tengo un problema, el siguiente comando me da el siguiente error:
`grupo50-> \copy Usuarios FROM '/home/grupo50/csv/Usuarios.csv' delimiter ',' header
ERROR:  relation "usuarios" does not exist`

Qué estoy haciendo mal?

**Comment by CmPoblete** [comment]
Creaste la tabla usuarios en psql?

**Comment by alanezz** [comment]
Primero tienes que crear las tablas en psql y después importar los datos.

Saludos.

**Comment by valerojasm** [comment]
Brp, que gil, muchas gracias!!!!

**Comment by jminostroza** [comment]
y luego en qué formato debería exportar las tablas hechas en psql para poder usarlas en php?
