### ISSUE TITLE
Separa query de php?

### ISSUE THREAD

**Issue by naquiroz** [IIC2413/Syllabus-2018-2#68]
Hay alguna forma de separara queries y codigo php en dos archivos distintos?

Lo que quiero hacer es como algo así (en python):

```python

with open('query.sql', mode=r, encoding='utf-8') as file:
    query = file.read()
```

**Comment by alanezz** [comment]
Lo único que se me ocurre por ahora es utilizar `include_once ` junto con los `define`, como cuando definimos el archivo de configuración. Dentro de los define pones el String de la consulta.

**Comment by naquiroz** [comment]
:+1: Gracias!, por curiosidad, es buena practica hacer eso? (separar las consultas del codigo)

**Comment by alanezz** [comment]
Tu código se va a ver más legible por lo que es buena idea. De todas formas uno en la vida no se enfrenta con este dilema, porque cuando se desarrolla una aplicación se tiende a usar un ORM que te abstrae del código de la base de datos, y ese código efectivamente está separado del html. Escribir php plano ya casi ni se hace.

Saludos.
