### ISSUE TITLE
[Impar] Tipo, fecha contratacion y expiración de seguros?

### ISSUE THREAD

**Issue by naquiroz** [IIC2413/Syllabus-2018-2#70]
En la entrega uno se decía que los seguros tenían un tipo, fecha de contratación y expiración, sin embargo ninguna de esas tres columnas se encuentran ni en los datos de `UsuarioSeguro.csv` ni `Seguros.csv`

Eso implica que eso ya no debemos modelarlo?

**Comment by alanezz** [comment]
Para esta entrega lo puedes omitir.

Saludos.
