### ISSUE TITLE
404 not found :c 

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [IIC2413/Syllabus-2018-2#71]
Me quedan algunas dudas con respecto a la pagina que tenemos que correr, en la issue del profe dice que [http://bases.ing.puc.cl/~grupoXX/nombre_del_archivo.php](url). Subi por filezilla los archivos de la ayudantia para intentar correrlos y luego intente corriendo el url reemplazando con el nombre de mi grupo y el nombre de alguno de los archivos .php pero no encuentra la pagina :c entonces no sé que me falta. En el link se van agregando los nombres de las carpetas? lo intente de varias formas y no me resulta. Ayuda porfi 😢

**Comment by CmPoblete** [comment]
Lo subiste a la carpeta sites?

**Comment by ValentinaAlvarezG** [comment]
no 🤔 intentare con eso

**Comment by ValentinaAlvarezG** [comment]
Ahi sii!! gracias c:
