### ISSUE TITLE
Falta el usuario 126 :((((

### ISSUE THREAD

**Issue by DanielCarrascoFalcon** [IIC2413/Syllabus-2018-2#72]
En el csv que muestra la relacion de cada usuario con los seguros, se tiene el id_usuario 126 pero no lo tengo regitrado como usuario por lo tanto no se carga la tabla en postgresql...
Lo he buscado incluso en las tablas del grupo par pero no está :c 
(Lo que encontré en la tabla par era que Falabella tiene ese id pero no sé si es correcto)

**Comment by alanezz** [comment]
Hola,

En clases (y otras issues) dijimos que esas anomalías las podían omitir.

Saludos.

**Comment by antoniacobo** [comment]
@alanezz y cómo se hace para omitirlas? He buscado en internet pero no he encontrado

**Comment by alanezz** [comment]
Hola, no se trata de omitir como tal. Es tratar de eliminar esas tuplas que no sirven. Por ejemplo, hacer una consulta del tipo `DELETE FROM` cuando ciertos `id` no estén en otra tabla. Pero pueden hacerlo como quieran.

Saludos.
