### ISSUE TITLE
Tiene sentido hacer subclases cuando estas no tienen atributos adicionales?

### ISSUE THREAD

**Issue by fedetaladriz** [IIC2413/Syllabus-2018-2#73]
Hola!
Básicamente, la pregunta es lo que sale en el título de la issue. 
Que pasa, por ejemplo, si tengo una clase padre, "persona" y tengo dos subclases,  "niño" y "adulto" que no tienen atributos adicionales respecto a la clase padre? En la clase de diseño de bdd se dice que lo correcto es hacer una tabla principal para la clase "persona" y una tabla para cada sublclase. Sin embargo, las tablas "niño" y "adulto" tendrían solo una columna cada una, por lo que me entró la duda respecto a que si será mejor colocar otra columna en la tabla "persona" que indique si es adulto o niño. 
Gracias!!

**Comment by rfenzo** [comment]
Hola, realmente depende del uso futuro y de calidad del modelo. Con lo anterior me refiero a que si en un futuro te das cuenta que sería útil guardar información dentro de una de esas subclases, el hecho de tenerlo en tablas separadas hace que solo tengas que agregarle un atributo, mientras que si actualmente lo guardas como un atributo en "persona", tendrías que modificar el esquema y cambiar todas las consulas que hayas hecho sobre este.

Claramente lo primero que menciono es preferible y representa un mejor modelo pues se puede extender facilmente.
