### ISSUE TITLE
Duda archivos ayudantía

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [IIC2413/Syllabus-2018-2#74]
Hola! no me queda muy claro que hace el archivo consulta.php de la ayudantía, versus los otros archivos de consulta como Consulta_Stats.php, son todos parte de lo mismo? porque por ejemplo por lo que pude entender, test.php es como un archivo aparte de los demás. Onda por qué consulta  se conecta a la base de datos con los archivos contenidos en config, y los demás de consulta con el sftp.json?

Ojalá me puedan ayudar :c

**Comment by alanezz** [comment]
Hola!

El consulta.php es un "template", todos los demás siguen esta idea, que básicamente es:

1. Hago un POST desde otro lado (en este caso el index)
2. Llego al php en particular que procesa la consulta
3. Defino la conexión
4. Escribo mi consulta y la ejecuto
5. Usando la función echo muestro todas las tuplas

Saludos!
