### ISSUE TITLE
Duda group by

### ISSUE THREAD

**Issue by DanielCarrascoFalcon** [IIC2413/Syllabus-2018-2#75]
No he logrado hacer funcionar las consultas que utilizan group by en postgresql...
En sqlite no hay problema al consultar, se supone que debo reformular las consultas o simplemente no puedo usar group by en postgresql??

**Comment by alanezz** [comment]
Hola, (como la issue estaba cerrada no sabía si contestarla, pero le puede servir a alguien)

Sucede que, como vimos en clases, cuando uno hace consultas `GROUP BY` y agrega atributos en la proyección que no están en el `GROUP BY`, la consulta se cae (con justa razón porque esto no hace mucho sentido).

Generalmente, el error es que SQLite te deja proyectar cosas que no están en el `GROUP BY` y PostgreSQL no. Pero esto es más bien un problema de la consulta, porque como vimos en clases esto no hace sentido.

En general todo lo que hace SQLite lo puede hacer Postgres (y mucho mucho más).

Saludos.
