### ISSUE TITLE
Servicios (par)

### ISSUE THREAD

**Issue by valerojasm** [IIC2413/Syllabus-2018-2#77]
Hola!

Tengo un problema con los servicios en los csv que nos entregaron. De la servicioscompra.csv puedo obtener varios id de servicio, y de aquí es también la única tabla de la que puedo extraer precio, descripción, etc. de estos. El problema es que faltan algunos que sí aparecen en TiendaServicioProducto.csv y que no tengo de donde sacar sus atributos, como el de id 1, 16 por ejemplo. No sé si no importan, o estoy haciendo algo mal?

Gracias de antemano!

**Comment by alanezz** [comment]
Hola,

En clases y en otras issues dijimos que esas filas se podían omitir.

Saludos.
