### ISSUE TITLE
Abonos, ¿no más de uno al día? + BCNF transacciones

### ISSUE THREAD

**Issue by jmwielandt** [IIC2413/Syllabus-2018-2#78]
Hola, no me cuadra que un usuario pueda abonar el mismo monto dos veces el mismo día (con igual valor del nebcoin) con la misma tarjeta sin tener un id_abono o similar que sí sea único. El NebBank no tendría cómo saber si un abono está repetido en la db o si de verdad el usuario abonó dos veces. Además eso dejaría esa relación sin primary keys 🤔 ¿Es necesario que todas las relaciones tengan llaves?

Es cierto que podríamos poner la restricción arbitraria de que no se puede hacer más de un abono al día pero no creo que sea solución. 

**Otra cosa:**
Si tengo:
id_usuario -> nombre, edad, etc
e id_transacción -> id_usuario_origen, id_usuario_destino, etc
¿Cuenta como BCNF?

**Comment by alanezz** [comment]
Hola,

Respecto a los abonos diremos que no van a haber anomalías. Puedes (y deberías) agregar una primary key como un id a los abonos si lo encuentras necesario.
En lo segundo está bien.

Saludos.

**Comment by jmwielandt** [comment]
Gracias! :D

**Comment by jmwielandt** [comment]
@alanezz Hola, aprovecho de referenciar a mi issue #87 y preguntar si ¿cuenta como anomalía que haya usuarios que realizaron abonos pero que no están en la base de datos de usuariosPagos que nos pasaron (entonces no tenemos datos sobre ellos)?
En concreto estos son los usuarios en cuestión
![imagen](https://user-images.githubusercontent.com/37153467/46248557-19ab6e00-c3f1-11e8-888f-3e26b1ab114e.png)

`select * from abonos where abonos.id_usuario not in (select id_usuario from
 usuarios);`

**Comment by alanezz** [comment]
Hola,

Como dije en clases, si tenían una anomalía de ese tipo, pueden tomar la solución que estimen conveniente. Lo que yo prefiero es no considerar esos usuarios.

Saludos.
