### ISSUE TITLE
Se debe descargar psql?

### ISSUE THREAD

**Issue by Mariana-Ortega-del-Rio** [IIC2413/Syllabus-2018-2#79]
Hola, 
Tengo una duda con psql. Una vez que me conecto al ssh (ya puse grupo25@bases.ing.uc.cl y mi password en la terminal), cuando hago psql grupo25 y pongo mi password no entiendo bien qué estoy haciendo exactamente. Puedo ahí mismo correr consultas o tengo que descargar psql en mi computador?

Saludos!

**Comment by alanezz** [comment]
Hola,

En el servidor está instalado psql, no lo necesitas en tu computador. La idea es cargar ahí los datos y correr consultas en el servidor.

Saludos.
