### ISSUE TITLE
GET para consultas select?

### ISSUE THREAD

**Issue by naquiroz** [IIC2413/Syllabus-2018-2#80]
Hola! Cuando hago consultas que solo entregan datos, qué es mas correcto? emitir  consultas por protocolo `GET` o `POST`? Por que a mi parecer, debería ser `GET` o no? Dado que estamos solicitando datos :thinking:

**Comment by alanezz** [comment]
Hola,

Tienes razón, pero por ahora no nos estamos preocupando de eso. Normalmente cuando sólo pides datos (y no insertas nada) se debería hacer un get, pasando los paramatros en la query de la URL. Pero vas a aprender más de eso en el curso de aplicaciones web en el futuro.

Saludos!

**Comment by naquiroz** [comment]
Oka! Pero está mal si lo dejo con `GET`?

**Comment by alanezz** [comment]
Obvio que no.

Saludos.
