### ISSUE TITLE
Seguro contratado más veces

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [IIC2413/Syllabus-2018-2#81]
Cuando se quiere mostrar el seguro que ha sido contratado más veces, si hay un empate entre dos o más seguros, deben mostrarse todos los seguros que tienen la misma cantidad? o solo uno (y en este caso sería medio al azar cual se mostraría)

**Comment by alanezz** [comment]
Hola,

Puedes hacerlo como estimes conveniente. Yo si hay empate mostraría los dos.

Saludos.
