### ISSUE TITLE
[Impar] Suma abonos o todos los abonos? Y en qué unidad?

### ISSUE THREAD

**Issue by naquiroz** [IIC2413/Syllabus-2018-2#82]
Hola! 
En el enunciado se pide la siguiente consulta;

![image](https://user-images.githubusercontent.com/29825816/46220103-8c4c1900-c31f-11e8-946f-76520d1c947e.png)

Lo que no entiendo es que si se debe entregar la suma de todos los abonos, por cada tarjeta de crédito, o si se debe entregar todos los abonos por cada tarjeta de crédito. Y lo otro, se debe entregar el resultado en `NebCoins`? o en pesos chilenos? Debemos ademas mostrar el precio de compra?

**Comment by alanezz** [comment]
Se supone que tu tabla abono debería tener el monto en clp y el valor de la nebcoin en ese momento. Lo que tienes que mostrar es algo así como: usuario - tarjeta - monto del abono en clp - valor de la nebcoin en ese momento. Si quieres puedes calcular el monto en NebCoins. Es como prefieras tú.
