### ISSUE TITLE
Comando permitidos

### ISSUE THREAD

**Issue by FernandoDeDiego** [IIC2413/Syllabus-2018-2#84]
Hola!
Me surgió la duda de si podemos usar cualquier comando de PSQL, o hay alguna restricción (como en la prueba que no podíamos usar LIMIT, MAX, etc).
Saludos!

**Comment by alanezz** [comment]
Hola,

No hay restricción.

Saludos.

**Comment by FernandoDeDiego** [comment]
Gracias!!
