### ISSUE TITLE
[impar][sql] Dudas SQL

### ISSUE THREAD

**Issue by jmwielandt** [IIC2413/Syllabus-2018-2#87]
Hola, intentando hacer las consultas del enunciado en psql me está arrojando cosas extrañas.

En la consulta 2 del enunciado impar intento hacer: 
```select u.id_usuario, t.numero_tarjeta, a.monto from usuarios as u, tarjetacredito as t, abonos as a where a.id_usuario = u.id_usuario and a.numero_tarjeta = t.numero_tarjeta;```
y me retorna 18 tuplas, pero en la relación de los abonos tengo 32, pero no sé qué estoy haciendo mal :(

También para la consulta 3 (ya lo solucioné de otra forma pero igual quiero saber) intenté hacer esto:
![imagen](https://user-images.githubusercontent.com/37153467/46239884-a7e20e80-c375-11e8-9840-2401a2535054.png)
Pero no sé por qué me retornaba todas las tuplas y no solo la con mayor "qtty" de todas :(
(Terminé usando tablas auxiliares con "with ... as ... " y me funcionó, hacer una vista no lo veo rentable).

**Comment by alanezz** [comment]
Hola, es por lo mismo de la issue #78, hay usuarios que no están en la BD. La consulta está correcta, así que tranquilo, es porque hay usuarios que tienes que omitir (o buscar una solución que tú consideres más elegante, pero queda a tu criterio)

Saludos.
