### ISSUE TITLE
Saldo usuarios [Impar]

### ISSUE THREAD

**Issue by CristobalHV** [IIC2413/Syllabus-2018-2#88]
Hola, estaba revisando las consultas del saldo de los distintos usuarios, ¿es normal que muchos me den MUCHOS usuarios con cifras negativas en su saldo? 🤔

**Comment by Taeval** [comment]
A mi me pasó lo mismo, creo que es porque en el csv con las transacciones, los usuarios que hacen un pago a alguien no reciben un pago (aparecen como usuario1 pero no como usuario2 en la tabla).  Por ejemplo, el usuario 111 aparece 2 veces como usuario1 en la tabla con las transacciones, pero nunca carga nebcoins y nunca recibe un pago.
