### ISSUE TITLE
[IMPAR] Duda consulta 5: resultados en notación científica

### ISSUE THREAD

**Issue by Taeval** [IIC2413/Syllabus-2018-2#91]
En la consulta 5 se nos pide mostrar la resta entre el monto total de la transacción y las cuotas pagadas. Algunas cuotas son periódicos aproximados y al hacer la resta se obtiene un resultado en notación científica. ¿Está bien así o podemos modificar los datos para evitar esto?

**Comment by nicoparraguez** [comment]
No bastara con sumar los valores de las que el booleano de pagado es 0? o hay que hacer esa resta con el monto total de la transacción

**Comment by alanezz** [comment]
Yo creo que la forma de @nicoparraguez es más simple, pero la otra también funciona. Da lo mismo si queda en notación científica.

**Comment by Taeval** [comment]
Perfecto, muchas gracias!
