### ISSUE TITLE
Error de conexion al servidor en FileZilla

### ISSUE THREAD

**Issue by sjkinast** [IIC2413/Syllabus-2018-2#94]
Hola, intente todas las combinaciones de grupo y servidor y no logro conectarme alguna idea de porque podria ser esto?

**Comment by alanezz** [comment]
Hola, podrías adjuntar un pantallazo de lo que estás escribiendo? Necesitamos más detalles para ayudarte.

**Comment by sjkinast** [comment]
![captura de pantalla de 2018-10-01 00-02-28](https://user-images.githubusercontent.com/37150014/46267850-8b78da00-c50d-11e8-97eb-cdd748a0ff3a.png)

**Comment by alanezz** [comment]
El puerto para acceder es el 22. El 5432 es exclusivo de PostgreSQL.

**Comment by sjkinast** [comment]
Si te fijas en la imagen también probe con el puerto 5432

**Comment by alanezz** [comment]
Por eso te lo menciono, porque ahí NO deberías colocar el 5432.

Saludos.
