### ISSUE TITLE
Captación de fechas en psql

### ISSUE THREAD

**Issue by nfbalbontin** [IIC2413/Syllabus-2018-2#97]
Hola, qué tal? 
Con mi compañero tenemos todo listo desde el viernes y hoy al probar por última vez las consultas la primera no funcionaba. Al revisar esto ingresé personalmente a la base de datos y traté de probar la consulta ingresándola por psql con una fecha en específica que formaba parte de las tablas entregadas. Al probarlo la consola me retornaba que la columna que estaba ingresando no existía. Cree de nuevo la tabla "transacciones" con sus respectivos parámetros por si por alguna casualidad el "type" que había ingresado no era DATE y continuó arrojando el mismo error. Luego probé consultas más simples como que me mostrara los datos de la tabla transacciones a partir de una fecha y nuevamente el mismo error. Después probé esa misma consulta con todas las otras tablas que tenían fechas y me arrojaron el mismo error. 
Probé con otros atributos, como id's u otros y estos si funcionaban. ¿ A qué se deberá esto? 
Adjunto fotos de los errores
<img width="372" alt="captura de pantalla 2018-09-30 a la s 22 03 59" src="https://user-images.githubusercontent.com/26261777/46265452-dd653400-c4fc-11e8-8c6e-41032a5055c7.png">
<img width="499" alt="captura de pantalla 2018-09-30 a la s 22 04 40" src="https://user-images.githubusercontent.com/26261777/46265456-e950f600-c4fc-11e8-91ca-a63bf2800daf.png">
<img width="448" alt="captura de pantalla 2018-09-30 a la s 22 03 50" src="https://user-images.githubusercontent.com/26261777/46265465-0f769600-c4fd-11e8-88f9-4a3d1b58ad52.png">
<img width="498" alt="captura de pantalla 2018-09-30 a la s 22 16 57" src="https://user-images.githubusercontent.com/26261777/46265622-937d4d80-c4fe-11e8-82d0-eb7337cee358.png">

**Comment by cmp831** [comment]
Para consultar fechas en Postgres debes hacer un cast a la columna, como se muestra [aca](https://stackoverflow.com/a/5875763)

**Comment by nfbalbontin** [comment]
me sigue arrojando el mismo error. Si la consulta que mostré anteriormente funcionaba hace dos días atrás
<img width="533" alt="captura de pantalla 2018-09-30 a la s 22 14 28" src="https://user-images.githubusercontent.com/26261777/46265598-50bb7580-c4fe-11e8-8989-1fcc7e5f2c51.png">
<img width="473" alt="captura de pantalla 2018-09-30 a la s 22 14 38" src="https://user-images.githubusercontent.com/26261777/46265600-51540c00-c4fe-11e8-9626-2de136d2d904.png">
