### ISSUE TITLE
Problema para iniciar sql en php

### ISSUE THREAD

**Issue by legramsch** [IIC2413/Syllabus-2018-2#98]
En la linea de php para crear el objeto de sql:

`$db = NEW PDO("PGSQL:DBNAME=Nebstore;PORT=5432;HOST=LOCALHOST;USER=grupo58;PASSWORD=grupo58");`

En mi computador funcionaba bien, pero al escribirlo en el servidor, el código me manda el mensaje:

`Fatal error: Uncaught exception 'PDOException' with message 'could not find driver' in /home/grupo58/Sites/prueba.php:10 Stack trace: #0 /home/grupo58/Sites/prueba.php(10): PDO->__construct('PGSQL:Nebstore=...') #1 {main} thrown in /home/grupo58/Sites/prueba.php on line 10`

¿De que puede ser ese problema? Buscando en internet sale que es que el driver para pgsql no está instalado o activado, pero de todas formas yo no puedo hacer eso sin privilegios.

**Comment by alanezz** [comment]
Hola,

El nombre de tu base de datos debería ser grupo58, no Nebstore.

Saludos.

**Comment by cmp831** [comment]
Hola, pruebalo usando los nombres de parametros en minuscula
`$db = NEW PDO("pgsql:dbname=grupo58;port=5432;host=LOCALHOST;user=grupo58;password=grupo58");`
